### ISSUE TITLE
Misleading documentation for Minimize.minimize - Minimize.params is not the same Parameters instance used to initialise the Minimizer.

### ISSUE THREAD

**Issue by andyfaff** [lmfit/lmfit-py#174]
Lets consider the following code:

    import numpy as np
    from lmfit import minimize, Parameters, Parameter

    x = np.linspace(0, 15, 301)
    data = (5. * np.sin(2 * x - 0.1) * np.exp(-x*x*0.025) +
            np.random.normal(size=len(x), scale=0.2) )

    # define objective function: returns the array to be minimized
    def fcn2min(params, x, data):
        """ model decaying sine wave, subtract data"""
        amp = params['amp'].value
        shift = params['shift'].value
        omega = params['omega'].value
        decay = params['decay'].value

        model = amp * np.sin(x * omega + shift) * np.exp(-x*x*decay)
        return model - data

    # create a set of Parameters
    params = Parameters()
    params.add('amp',   value= 10,  min=0)
    params.add('decay', value= 0.1)
    params.add('shift', value= 0.0, min=-np.pi/2., max=np.pi/2)
    params.add('omega', value= 3.0)

    # do fit, here with leastsq model
    result = minimize(fcn2min, params, args=(x, data))

    print result.params is params

The last line prints `False`.  i.e. `result.params` is not the same instance as the `params` that was used to construct the `Minimizer` object.  This is because in `Minimizer.unprepare_fit` there is a deepcopy:

    self.params = deepcopy(self.params)

I would naively expect
    
    result.params is params

to be `True`.  Why is a copy done in `unprepare_fit`? Is it done to keep the initial `Parameters` object unchanged?  If so, then it would be better to do the deepcopy before `Minimizer.minimize` is called.
For example you could have the confusing behaviour:
     
    obj = Minimizer(fcn2min, params, args=(x, data))
    #prints True
    obj.params is params
    obj.minimize()
    #prints False
    obj.params is params

**Comment by danielballan** [comment]
@andyfaff Above, Matt alluded to an earlier discussion on this copy-on-input issue. It was in #56. His key points are in [this comment](https://github.com/lmfit/lmfit-py/issues/56#issuecomment-30375780). I agree with some of those points, in particular that changing to copy-on-input would break a lot of old user code. The original poster of that issue suggested working around the problem by implementing a new class, `Model`. Which, of course, we did.

At the time, Matt [suggested](https://github.com/lmfit/lmfit-py/issues/56#issuecomment-30385200) adding warnings about the copying behavior in 0.8 and switching to fully copy-on-input in version 0.9:

> I wonder if it might reasonable to implement copy-on-output (and `reset()` and `copy()` [methods for `Parameter` objects]) for 0.8.0, and change all the examples and docs to use `Minimizer.params` instead of the params argument, and deprecate this usage so that with 0.9.0 params becomes copy-on-input? I've never thought that far in advance about API changes or version numbers, but perhaps this is the right approach.

As far as I know we never revisited that discussion, focusing instead on fleshing out `Model`.

**Comment by andyfaff** [comment]
@danielballan, I've just read (and re-read) through #56 to make sure I understood what was discussed at that time.
To recap the original issues boiled down to usage of the `minimize` **function**.  There were two calls to `minimize`, each had used the same `params` instance as the initial guesses, but the data was different in each case.  The output from each of those calls was `out1` and `out2`.  The problem was that `out1.params` and `out2.params` were the same, even though the data in the two fits were different.  This was a consequence of the same `params` instance being reused throughout the call chain.  In other words `params`, `out1.params` and `out2.params` were the same instance. These statements:

    params is out1.params
    params is out2.params
    out1.params is out2.params

would have all been `True` in the original issue.  The solution was to perform a `deepcopy` of `params`, but such that:

>params is altered to have the best values, correlations, and so forth

and

>out1.params is a copy of this, so that later work with `params` does not alter the fitter results.

This `deepcopy` operation was added to the underlying `Minimizer.unprepare_fit`.  The reason it was added there is so the original input `params` could be altered to have the best values.  However, it could have also been implemented as follows:

     def minimize(func, params, *args, **kwds):
          output = Minimizer(func, params, *args, **kwds)
          #do the minimization on the original params so they're updated.
          #here we are assuming that the deepcopy in unprepare_fit is not done.
          output.minimize()

         #now copy so that output.params and params are not the same instance
          par_copy = deepcopy(output.params)
          output.params = par_copy
          return output

This implementation still has the overall effect of modifying the original `params`, but the `output.params` is a copy, so that future work with `params` does not alter the `output.params`.  

I totally agree that this is the desired type of functionality for the `minimize` **function** and we wouldn't want to do anything to change this behaviour whatsoever.
Where I do feel there is room for improvement is in the `Minimizer` class.  Take the following example:

    import numpy as np
    from lmfit import Parameters, report_fit, Minimizer

    x = np.linspace(0, 1, 100)
    y1 = 1.0 * np.exp(1.0 * x)

    def residual(params, x, data):
        a = params['a'].value
        b = params['b'].value
        model = a * np.exp(b * x)
        return (data - model)

    params = Parameters()
    params.add('a', value = 2.0)
    params.add('b', value = 2.0)

    fitter = Minimizer(residual, params, fcn_args=(x, y1))

    #do an initial fit with something other than leastsq
    fitter.minimize(method='nelder-mead')

    print "\n params from first fit"
    report_fit(params)

    #now use leastsq to polish
    fitter.minimize(method='leastsq')

    print "\n params from polishing"
    report_fit(params)

This results in:

    params from first fit
    [[Variables]]
        a:   0.99999317 (init= 2)
        b:   0.99998273 (init= 2)
    [[Correlations]] (unreported correlations are <  0.100)

    params from polishing
    [[Variables]]
         a:   0.99999317 (init= 2)
         b:   0.99998273 (init= 2)
     [[Correlations]] (unreported correlations are <  0.100)

You'll notice:

1. The first fit changes the original `params` instance.
2. That after the polishing fit no uncertainties appear to have been added to the `params`  instance.
3. The report says that the initial values were 2 for the second polishing fit.  

If I had done the fit report using the `fitter.params` instance we would seen different results.  The reason behind this is the `deepcopy` done in `fitter.unprepare_fit`.  Everytime one calls the `fitter.minimize` method the `fitter.params` instance changes. Obviously, I would expect the values inside the `fitter.params` instance to change, but in this case it's a totally new object.  In a class based minimizer, such as `Minimizer` I would expect the `fitter` instance attributes created during initialisation to point to the same object throughout the object lifetime.
There are several examples for why this is important:

    import numpy as np
    from lmfit import Parameters, report_fit, Minimizer

    x = np.linspace(0, 1, 100)
    y1 = 1.0 * np.exp(1.0 * x)

    def residual(params, x, data):
        a = params['a'].value
        b = params['b'].value
        model = a * np.exp(b * x)
        return (data - model)

    params = Parameters()
    params.add('a', value = 2.0)
    params.add('b', value = 2.0)

    fitter = Minimizer(residual, params, fcn_args=(x, y1))

    #fit the original dataset
    fitter.minimize()

    report_fit(fitter.params)

    #let's simulate the data updating from time to time
    y1 *= 2

    #lets try fitting the data again 
    fitter.minimize(method='leastsq')
    report_fit(fitter.params)

This results in:

    [[Variables]]
    a:   1          +/- 0        (0.00%) (init= 2)
    b:   1          +/- 0        (0.00%) (init= 2)

    [[Variables]]
    a:   2          +/- 0        (0.00%) (init= 1)
    b:   1          +/- 0        (0.00%) (init= 1)

Here the underlying data is changing but we can reuse the `fitter` instance after the update.  This is because the `fitter.userargs` attribute always points to the same arrays.  If we had deepcopied the elements in `fcn_args` when initialising `fitter` then we would not be able to reuse `fitter` after the data had changed.  When I originally created this issue I was experiencing problems in a GUI where I storing all the `params` instances in a dictionary, displaying and editing them in a GUI.  On creating a `Minimizer` and then calling `fitter.minimize` several times I was noticing that the relevant `params` ***was updating the first time, but not after that***. This behaviour is inconsistent.  The only way to get around this was to overwrite the entry in `P` after every fit:

    params = P['dataset1']
    fitter = Minimizer(residual, params, fcn_args=(x, y1))
    fitter.minimize()
    P['dataset1'] = fitter.params

The last line should not be necessary. As far as I can tell there are no drawbacks from removing `deepcopy` in `fitter.unprepare_fit`.  The `fitter.params` attribute will then always point to the same `params` instance used to initialize the `fitter` object.  The only thing one has to do is write a slightly modified `minimize` *function* so the original issue, #56, does not reappear.  

I'm willing to write the PR for this.

**Comment by danielballan** [comment]
I agree that this particular aspect of `Minimizer` should be changed, and I think I agree that refactoring `minimize` and `unprepare_fit` makes the change effectively without side effects.

A PR with tests will help us all understand the gist of this. Please include tests on `minimize` and `Minimizer`, drawing on the examples and those in #56, so we can be sure that most usages are not changed. It would help to run the tests before changing the code, showing which pass and fail before and after.

**Comment by newville** [comment]
@andyfaff -- I'm still not sure I actually understand the points you're trying to make.  They seemed quite confusing to me, and your examples don't really illustrate clear points to me.   I'd much prefer to have a real conversations than long monologues that talk past each other, but I'll avoid the temptation of responding to your specific points, especially as I don't really understand them,  and have already asked several questions that have gone unanswered.  I'm sorry this is as long as it is, and I am beginning to despise github Issues, so I apologize in advance.

*I* think the basic problem here is that when one does successive fits with the same ``Minimizer.minimize`` or ``minimize`` function, one may one to save intermediate results, and have the best-values-so-far be used as starting values for the next fit.  But If one wants to keep a copy of the parameters for successive fits, I don't see how it's possible to avoid doing a copy of the `params` at some point. The only questions are where this happens, and whether the user has to do it explicitly.

Again, I'm not completely sure this is what you think the Issue is (you keep going on about object identity....), but that's the only actionable issue I can see here.

Also: I'm not saying that the current behavior for how ``params`` are handled in the ``Minimize`` class is the best behavior.  I even gave a proposed solution (copy on input) earlier in this conversation, as was discussed a year ago too (my preference for mailing list grows with each conversation).  At that time copy on output seemed like the least disruptive approach.  More options are given below.

I'll skip the majority of your post, and skip to the actionable items:

>    As far as I can tell there are no drawbacks from removing deepcopy in fitter.unprepare_fit.  

The user would have to explicitly copy the parameters if they wanted to keep intermediate results for successive fits.  That is a drawback.

> The fitter.params attribute will then always point to the same params instance used to initialize the fitter object.

I just don't understand why the identity of `fitter.params` and `params` important.  The **values** of those objects are definitely important.  But why do you need two names bound to the same object?  If anything, that seems like a (probably benign) problem to me.  In any event, identity of an object's attributes should be considered an implementation detail.

> The only thing one has to do is write a slightly modified minimize function so the original issue, #56, does not reappear.

I think the ``minimize`` method and function should have very similar behaviors, and that the function should be a trivial wrapping of the method.  Doing otherwise opens up room for incompatibilities and headaches.   I see a a few possible approaches to improving what `Minimizer.minimize` and the `minimize` function does with `params`:

  1. leave as is.  Users would have to make copies of params between subsequent uses of the `Minimizer.mimimze` method.  This requires no code changes, but clarification of docs and examples.

  2. have copies made only in the `minimize` function.  Copies would still have to be made explicitly by the user when using the `minimize` method.

  3. Copy `params` on input (in `__init__()` or `prepare_fit()`).  This would leave the original parameter values unchanged.  A user would still have to make explicit copies to retain intermediate fits.  This would potentially break some existing scripts.

  4. Have `Minimize.minimize` method return an object (`MinimizeResult`, akin to `OptimizeResult` or to `ModelFit`) that would contain statusinformation and a copy of the `self.params` after the fit.  This class could also have a `fit_report` method, similar to `ModelFit` (for uniformity, perhaps `ModelFit` should be renamed `ModelResult`? I think there's little harm in that).  In this option, `Minimizer.params` would not need to be re-copied internally (which is, I think, partly addresses your concern), and each successive fit would have the last best values as starting  values.  `Minimizer.__init__()` could either have the passed in `params` be copied on input or be identical to `self.params`.  Since we'd be breaking stuff anyway, I would suggest copy-on-input to be better, but could go either way.  In this scheme, the `minimize` function would return the same output, leaving it a trivial wrapping of `Minimize.minimize()`.  This would break some existing scripts, but would also allow for more flexibility in what is included in the return value.

Option 1 is the least work, but clearly confusing.  I think Option 2 is confusing too.  Option 3 is probably better than 1 or 2, but I don't know that it really solves the core issue, and may be nearly as confusing to the current behavior.  My preference would be for Option 4: it is the most work, but probably the best long-term solution.  If we're going to break things, we might as well make it worth the effort.

I would be eager to hear opinions on this, and especially whether you think option 4 would satisfy the "Issue" as you see it.  

Again, sorry this post was so long.
