### ISSUE TITLE
Using arbitrary numbers of arguments in a fit function (*args)

### ISSUE THREAD

**Issue by pomalley** [lmfit/lmfit-py#179]
I have a fit function that I generate dynamically with the call signature `f(x, *args)`. Is there a way to generate a Model with this function? `mod = lmfit.Model(f)` returns a model with no parameters, and `mod = lmfit.Model(f, param_names=['p1', 'p2'])` gives `ValueError: Invalid parameter name...`

**Comment by newville** [comment]
@pomalley, @andyfaff   Sorry for the delay in responding. 
 
As Andrew suggested, lmfit's Model class inspects the model function to create its parameters, and does not support `*args` arguments.   It might be possible to allow arbitrary, unnamed positional arguments, but the mapping of the parameters you name onto those positional arguments would have to be worked out, and I'm not sure it would be able to satisfy every need (for exmple, if you have some explicitly named positional arguments and `*args`, how would you assign automatic names to `*args`?).   It's not clear to me what the benefit of having this feature would be.

But that response addresses the "Issue" you raised ("Using arbitrary numbers of arguments in a fit function (*args)"), and may not help with what you actually want to accomplish. You didn't provide many details for what you want to do, only that what you tried that didn't work the way you thought.  This is kind of an unfortunate consequence of raising "Issues" instead of asking questions -- it puts you in the place of thinking you are identifying a shortcoming of the code and us of in the defensive position of accepting your premise and trying to address why what you tried didn't work, instead of focusing on what you are actually trying to accomplish.   If you had asked a question like "how can I do this..." on the mailing list, you might have received very different responses.

For example, if you're generating model functions dynamically, why can't you generate function argument names, or use `**kwargs` instead of `*args`?   If those are impractical, perhaps the `ExpressionModel` class would be of use to you?   I don't know for sure that any of these approaches would work for what you want to do, but the conversation probably would have been very different if you had asked "how do I do something?" instead of asking "why didn't the thing I tried work as I expected?".

Sorry, I don't mean to pick on you specifically for "asking a dumb question", this is really meant to be addressed to everyone, as a mailing list message would be.

**Comment by pomalley** [comment]
I definitely intended to raise a question rather than an issue; perhaps I could have phrased it better.

1. I had no idea there was a mailing list--perhaps add it to the readme that shows up on the github main page? Maybe I should have just looked at the web page ;-). 
2. I also intended to tag this issue as "question", which I thought one could do on Github, but I couldn't do that on this project--permissions I guess.

In any event I have it working with `Minimize` which is still very easy to use. Thanks for the great code!
