### ISSUE TITLE
Possible uncompleted test

### ISSUE THREAD

**Issue by tritemio** [lmfit/lmfit-py#184]
I noticed that [this test](https://github.com/tritemio/lmfit-py/blob/eae879458a82802c168259d78a8e1f7fad8c9d2e/tests/test_model.py#L197) may be missing a final assertion.

If my interpretation is correct it needs to be fixed.

**Comment by newville** [comment]
OK to close this?

**Comment by danielballan** [comment]
I don't think so. Was it fixed and I missed it? I think is my code. I can
patch this week.

**Comment by danielballan** [comment]
Did we accidentally or intentionally put some state into `Model`? I expect this to fail:

    model = lmfit.models.GaussianModel()
    guess = model.guess()
    del guess['sigma']
    model.fit([1,2,3], x=[1,2,3], **guess)

but it passes because `model` falls back on `param_hints`. I expect this kind of behavior from `Fitter`, but not `Model`.

**Comment by tritemio** [comment]
The parameter hints set condition of sigma > 0 that is structural for the GaussianModel and always applied (unless explicitly overridden calling `set_param_hint`). 

It is not clear to me why your example does not fail since you don't give any initial value  for sigma (just a boundary set from the hints).

**Comment by newville** [comment]
It works if you delete 'center' too.   I think this is because GaussianModel wraps a function with default values for all parameter values, so that it is acceptable to not include a 'sigma' or 'center'.

I don't know if "default value" is "state", exactly -- perhaps "class-wide state"? .    
Do you think we should remove the default values?

**Comment by newville** [comment]
I think this has been addressed.
