### ISSUE TITLE
scalar_minimize does not reset stderr and correl when a Minimizer instance is reused.

### ISSUE THREAD

**Issue by andyfaff** [lmfit/lmfit-py#189]
`scalar_minimize` does not calculate parameter uncertainties (Related to #169).  As such, I would expect the `stderr` and `correl` attributes to be `None` if I do a fit using that method. Indeed, a `Parameter` is initialised with `None` for those attributes.

However, if you have done a fit previously with `leastsq` the `stderr` and `correl` will have been calculated.  If you then refit the data with `scalar_minimize` the `stderr` and `correl` attributes are not reset to `None` and you are left with stale values.  The following code illustrates the problem:

    from __future__ import print_function
    from lmfit import Parameters, Minimizer, fit_report
    from numpy import random, linspace, pi, exp, sin, sign
    from copy import deepcopy
    
    p_true = Parameters()
    p_true.add('amp', value=14.0)
    p_true.add('period', value=5.46)
    p_true.add('shift', value=0.123)
    p_true.add('decay', value=0.032)
    
    def residual(pars, x, data=None):
        vals = pars.valuesdict()
        amp =  vals['amp']
        per =  vals['period']
        shift = vals['shift']
        decay = vals['decay']
        if abs(shift) > pi/2:
            shift = shift - sign(shift)*pi
        model = amp * sin(shift + x/per) * exp(-x*x*decay*decay)
        if data is None:
            return model
        return (model - data)
    
    noise = random.normal(scale=0.7215, size=1001)
    x     = linspace(0., 250., 1001)
    data  = residual(p_true, x) + noise
    
    #create another dataset with different values
    p_true2 = deepcopy(p_true)
    p_true2['amp'].value = 5
    p_true2['period'].value = 10
    data2  = residual(p_true2, x) + noise
    
    fit_params = Parameters()
    fit_params.add('amp', value=13.0)
    fit_params.add('period', value=2)
    fit_params.add('shift', value=0.0)
    fit_params.add('decay', value=0.02)
    
    mini = Minimizer(residual, fit_params, fcn_args=(x,), fcn_kws={'data':data})
    mini.minimize(method='leastsq')
    print(fit_report(mini.params))
    mini.userkws = {'data': data2}
    mini.minimize(method='nelder-mead')
    print(fit_report(mini.params))

Results in:

    [[Variables]]
    amp:      13.8883869 +/- 0.149409 (1.08%) (init= 13)
    period:   5.45389166 +/- 0.027174 (0.50%) (init= 2)
    shift:    0.12329457 +/- 0.014567 (11.82%) (init= 0)
    decay:    0.03226311 +/- 0.000396 (1.23%) (init= 0.02)
    [[Correlations]] (unreported correlations are <  0.100)
    C(period, shift)             =  0.793 
    C(amp, decay)                =  0.585 
    C(amp, shift)                = -0.291 
    C(amp, period)               = -0.236 
    C(shift, decay)              = -0.179 
    C(period, decay)             = -0.145

for the first fit and 

    [[Variables]]
    amp:      5.01674659 +/- 0.149409 (2.98%) (init= 13.88839)
    period:   10.2063042 +/- 0.027174 (0.27%) (init= 5.453892)
    shift:    0.10819598 +/- 0.014567 (13.46%) (init= 0.1232946)
    decay:    0.03253109 +/- 0.000396 (1.22%) (init= 0.03226311)
    [[Correlations]] (unreported correlations are <  0.100)
    C(period, shift)             =  0.793
    C(amp, decay)                =  0.585
    C(amp, shift)                = -0.291
    C(amp, period)               = -0.236
    C(shift, decay)              = -0.179
    C(period, decay)             = -0.145

for the second.  As you can see the values for the second fit are 'correct', but the `stderr` and `correl` are stale from the previous fit.

**Comment by andyfaff** [comment]
I can write a PR to fix this.  Should the `stderr` and `correl` be reset in `prepare_fit`?

**Comment by andyfaff** [comment]
It gets slightly worse. Now lets fix a parameter (after previously letting it vary in a leastsq fit):

    >>>mini.params['amp'].vary = False
    >>>mini.minimize(method='nelder-mead')
    >>>print(mini.params['amp'].stderr)
    0.137414374655

Oops, the stderr is still there even though the parameter is fixed.

**Comment by newville** [comment]
@andyfaff:   I'm choosing to read this Issue as starting a conversation with "What should the behavior be in his situation?" rather than reading it as saying "the current behavior is wrong".    That is, when you do:

> mini = Minimizer(residual, fit_params, fcn_args=(x,), fcn_kws={'data':data})
> mini.minimize(method='leastsq')
> print(fit_report(mini.params))
> mini.userkws = {'data': data2}
> mini.minimize(method='nelder-mead')
> print(fit_report(mini.params))

you are intentionally re-using many parts of the "state" from the first fit: the `mini` minimizer and its parameters for sure.  You *explicitly* changed the `userkws['data']` and the minimization method.   You *could have* changed the objective function and/or any properties of the the parameters.  But,  clearly, you intended to *not* change these and to keep many of the properties of the parameters (say, the value, any bounds, and whether it is fixed). 

Given that, it's not entirely clear that we *should* be changing parameters properties implicitly.   Like, I can see that the `stderr` would be stale in this case, but that's really because the scalar minimizer didn't set it.

I think I would prefer to have the scalar minimizers explicitly set `stderr` and `correl` to `None` for each parameter on output.  That is, it seems better to me to insist that all the fitting methods explicitly set these properties, and those that cannot set them should explicitly set them to `None` on output.  

Does that seem reasonable to everyone?   One disadvantage (vs current behavior) is that the confidence interval code could not be run after a scalar minimization, at least not until the scalar minimization routines are updated to explicitly calculate the uncertainties, say with the numpydifftools as suggested by @Tillsten. 

As for setting `param.vary` to `False` and it still having a non-`None` value for `stderr`, I think  I disagree that this is worse.     If `vary` is `False` you should know that `expr`, `min`, `max`, `stderr`, and `correl` are not valid.   There is potential harm in automatically changing these properties because the parameter is currently fixed -- it be set back to varying, and you wouldn't want to lose those values.  I'm OK with explicitly setting `stderr` and `correl`  to `None` after a fit that cannot estimate these (for any reason), but I don't think there should be special behavior just because a parameter is fixed (or constrained).
