### ISSUE TITLE
Why are the models stateless?

### ISSUE THREAD

**Issue by Luindil** [lmfit/lmfit-py#197]
Hi all,

i am currently writing an open source peak fitting software based on lmfit, pyqtgraph, numpy, spicy and pyqt4. The repository is https://github.com/Luindil/PeakThis. The idea is to use the model interface lmfit provides and add as many models to the graph by click defining the parameters (e.g. for a gaussian first click defines height and position, second click defines fwhm/sigma).

In the process of writing this software i find it unnecessary hard to work with the stateless models and to always use the parameter objects, especially for the resulting compound objects. I kind of have to always work around this implementation and try to keep the parameters in the models (i subclassed them).

In my opinion this stateless approach is not what i would like the models to behave. The use-cases i imagine are always including the parameter state saved in the model and then for example just calling eval(x) gives me the y-values. In any case the parameters are actually saved all the time as param hints in the model. So why not just use them? I think that would make the interface much easier to work with and then there is also no need for prefixes for same class model objects in composite models, because the composite model should know where which param was written too. In any case the parameter sigma/fwhm itself does not really make sense on its own since you always need also the peak shape to it, which is not saved in the parameter objects.
If somebody needs a specific compound model as the same starting model for several files fitting, it could just be created by deep-copying the starting model.

Can somebody explain me the rational and use-case for the current implementation of the model class? Why is there a need for the parameter objects? 

Best wishes
Clemens

**Comment by danielballan** [comment]
Take a look at #56 and #57 for the genesis of `Model`.

You have described a situation where it indeed would be convenient to recall the previous fit. On the other hand, when a user is applying the same `Model` to many different data sets, it may be better for the `Model` to be "fresh" and identical each time. To address these two needs, we have added a `Fitter` class, a stateful elaboration of `Model.`

This layered approach to the design of lmfit allows users to choose the tool that is only as "smart" as they want it to be. We have avoiding packing *all* of this logic into the `Model` layer.

Take a look at `Fitter` and see if it fits your needs. There is also `NotebookFitter` and `MPLFitter`, which add a GUI, but the basic `Fitter` can be considered just a stateful `Model`.

As for the `Parameters` class: they let you specify bounds, and they can be held fixed in a convenient way. These useful features are not available in the underlying scipy routine.

**Comment by Luindil** [comment]
Hei Dan, 

thank you for the response, i haven't seen the Fitter classes yet. I basically wrote the same one my own with some extra stuff...

I always hear in the discussion of having stateless models this example of fitting to many data sets, which i think is a special use case not the normal use case when somebody starts to use the library. And i think this special use case can be easily treated by just creating a start model and deep-copy it for every  file/fit. The overhead would be minimal. I do not understand why the model interface has to be created around this use case, which makes normal usage more complicated to work with.

What i mean in total, is for example adding together several gaussians without the need of creating namespaces for them (_prefix) fit the composite model and the individual models are automatically updated.

I have no problem with working around the current implementation. But i think it could be more simplified.

Best,
Clemens

**Comment by danielballan** [comment]
Perhaps we can feature the Fitter model as the natural choice for a new
user in the docs. Changing the behavior of Model at that level would break
a lot of user code, so I think this is a matter of presentation.

**Comment by newville** [comment]
Hm, let me start with an aside: Looking back at those older conversations, I wonder if maybe this is at least partially related to the confusion that lead to #174.      That is, separate from having Models (which is great), the original issues may have been solved more directly if  `minimize()` and `Minimizer.minimize()` returned an object that had a `params` attribute (along with, say fit statistics) that was a **copy** of the parameters used in the fit.    That would be a disruptive change, but might be for the best.  I think it might have negligible impact on Models, but it might clarify questions about "state of parameters", and if that had been clear for `minimize`, it might have impacted how we got to `Model`.   Any thoughts on that?

More on topic:

I don't have a strong preference for Model having parameters or whether one needs clearly separated Model and parameters.  It seems that Model-with-parameters would make the simplest case even simpler.   I think it would just be "different" for scripts with medium-sized models.    I guess the question boils down to how one re-uses Models:  Are you more likely to make a single Model and apply it to different data sets or make a new Model for each fit?     I can see that someone writing a GUI might have a very different approach to someone writing scripts here.   I think we'd want to favor making things easy for the "script writer", as the GUI write knows they're going to have to keep state somewhere.

I think there are enough people writing large, complex scripts and/or GUI-like apps using Models and composite Models that it's worth hearing from everyone how they'd like this to work.   I'd be willing to change the behavior if there is a consensus, but would hope any change was more or less final.

**Comment by tacaswell** [comment]
Managing state should be the responsibility of the user, not the library.  Having too much state buried under the covers also makes keeping track of provenance very difficult (as there is hysteresis) and opens the door to 'interesting' bugs due to side-effects. 

I very much disagree that batch fitting is the special case, interactive fitting is the special case (in terms of number of times the fit is actually called, ).   Why make user have to actively work against/remove functionality from the library?

I very much like the layered approach, base classes at the bottom that are stateless with 'convenient' stateful classes built on top.

**Comment by newville** [comment]
@tacaswell -- I think objects need *some* state, it's just a question of how much.  A GaussianModel does have an implied model function, for example.

>  I very much disagree that batch fitting is the special case, interactive fitting is the special
>  case (in terms of number of times the fit is actually called, ). Why make user have to 
> actively work against/remove functionality from the library?

I completely agree with you -- basic, batch scripts should be the main use-case, and long-running applications that want to re-use Models or Minimizer instances should be the exception.

**Comment by tacaswell** [comment]
@newville I should clarify, what I mean by 'state' is 'mutable state'.

**Comment by newville** [comment]
@Luindil, @danielballan, @tacaswell  -- Perhaps the Fitter class needs better advertisement and documentation?

I agree that, all things being equal, classes with minimal mutable state are preferred, but sometimes the purest solution isn't so useful in practice.   If one is using a batch script, the difference between stateful and non-stateful Model is probably minor, as the state won't persist (one can just re-run the script).   For a larger, application where one would do many fits on similar models, the difference could matter more.  Since that is the use-case that Clemens is talking about, it seems worth paying attention and not dismissing simply because it doesn't align with the prevailing theory.

A fit of a parametrized model function to some data definitely does have (mutable) state, and the point of the library is to help users to do fits to particular sets of data with particular models and parameters.  So I think questions about the need for the user to separately manage a Model and a set of parameters (especially as they aren't totally independent things) are likely to be raised again. 

Is anyone willing to write up a description of why "stateless Model" is preferred for the documentation (perhaps for `faq.rst`), and maybe include a work-flow case?

**Comment by Tillsten** [comment]
@tacaswell I disagree, for me, the aim of lmfit is to make data-fitting easy. This includes handling state. I would even go so far, that this problem is one of better applications of state-full objects. There a probably different preference depending on the type of user: People like me who work solo on their data-analysis and data-acquisition stack are quite about ever kind work which is done by package, people who work in bigger groups on bigger problems have probably other concerns. (I still stand by my point that models are cheaply created and/or copied that putting state in them is of no concern, but that ship has sailed). I would also bet a considerable amount of beer on the fact that batch fitting is the special case in _usage_. 

When i am doing any kind of complicated fitting with lmfit, i normally don't use lmfits models, because i am missing out on some easily obtainable optimization, e.g. fitting 120 peaks can be quite easily done with numpy broadcasting. That also  one reason why i am more inclined to tailor lmfit for small-scale usage, but of course, why not both :+1: .

**Comment by newville** [comment]
@Tillsten, @tacaswell :  Thanks, Till.  I admit to being somewhat uncertain about the right balance for this myself.   

I think it's clear that the "data" does not belong to the Model -- the model is independent of the data.  But the Parameters are sort of in between.  The Model defines and requires the names of the Parameters (suggesting a tight coupling, possibly ownership), but the values, bounds, etc for those Parameters don't really go with the abstract Model, but are more like the data -- specific to a particular fit to a particular set of data.  *That* suggests the looser coupling of the current behavior.

Like you say, Models are easy to make, so don't necessarily need to be so abstract that they are completely independent of a particular usage.  A completely abstract "Gaussian" or even "2 Gaussians plus a Line"  that has no Parameters at all seems to have very limited value.   So, like you, I think Model might be a case where a class having state is reasonable.

Currently, one *must* do 

```python
model  = SomeModel()
pars = model.make_params(...)
# maybe do some custom settings for pars
initval = model.eval(params=pars, ....)
result  = model.fit(data, params=pars, ...)
```

at which point one is more likely to use `result.params` than `pars`.  This leaves the fair question of "why do we have to explicitly make `pars` instead of manipulating `model.params`?".    I'm not sure I have a good answer to that.   Why not do this:

```python
model = SomeModel()
# maybe do some custom settings for model.params, possibly model.guess(....)
initval = model.eval(....)
result  = model.fit(data,...)
```

I'm not fundamentally opposed to changing the behavior so that a Model has a set of Parameters.   But I think we would need to come to a consensus to make such a change.   I think it basically comes down to usage:  How likely is it to reuse an instance of an abstract Model and want no parameters associated with it?

**Comment by tacaswell** [comment]
I am glad we all agree data does not belong to the model.

Once you have run a fit, the result of that fit (that is the values of the parameters generated by running the fit) belong to the result object, not the model object.  If it is convient to have the _guess_ parameters belong to the model that seems reasonable, so long as any methods that use it can also have the user pass in values.

I would expect that:

```python
model = SomeModel()
# do stuff to set up initial data
model2 = deepcopy(model)
res = model.fit(data, ...)
assert_equal(model, model2)
```

and 

```python
model = SomeModel()
res1 = model.fit(data, ...)
res2 = model.fit(data, ...)
assert_equal(res1, res2)  # at least for deterministic fitting methods
```

**Comment by newville** [comment]
@tacaswell  That seems reasonable to me.  I think it's actually closely related to #174,    That is, if `Minimizer.minimize()` treated its `params` member as initial guesses that were not changed by the fit,  and returned an Result object that had the best fit params and fit statistics particular to that exact fit, then it would not have varying state.  It would produce a result instead of implicitly altering itself.   

The `Model` class could do the same: have `params` that hold initial values and settings but not changed by the fit.   The fit result would hold the updated parameters. 

I think that would satisfy your two reasonable expectations.    And, if a user wants to do a fit, then make some adjustments to the parameters they could do something like:

```python
model = SomeModel()
# set up initial values for model.params
res1 = model.fit(data, ...)
# use these params as the initial values for next fit:
model.params = deepcopy(res1.params)
# make some more modifications to model.params
res2 = model.fit(data, ...)
```

Would this be acceptable to all?:  Have a `model.params` that holds settings and initial values, but is not updated with final values after a fit -- one needs to use the result to see those.   Is this preferable over current behavior?

**Comment by tacaswell** [comment]
Yes, that is exactly the sort of thing I had in mind.  It would probably also be good to let `fit` take initial guess as an optional arguement (and fall back to the `Model` object's value) so 

```python
model = SomeModel()
res1 = model.fit(data, ...)
res2 = model.fit(data, init_params=res1.params, ...)
```

would work as expected.

**Comment by licode** [comment]
I think this is convenient enough, and what I expected. Users can choose either initial values or the previous fitting results as the inputs for next fit, without touching the model.

**Comment by newville** [comment]
I think we can close this now
