### ISSUE TITLE
Add more tests using pandas Series

### ISSUE THREAD

**Issue by danielballan** [lmfit/lmfit-py#239]
The pandas support is tested, but only lightly. Prompted by #238.

**Comment by newville** [comment]
@danielballan  Yes, I agree.   And, I could not reproduce the error presented by @HamishBrownPFR, but was able to satisfy myself that pandas.Series as both `data` and `weight` were OK in `Model._residual`.   

Anyway, I'll try to convert that script to an actual test, and also to use the straight `minimizer` interface.   I think this all OK in the current code, but I'm not 100% sure I understand what the problem was.....
