### ISSUE TITLE
Python3 - parameters have no stderr

### ISSUE THREAD

**Issue by kmiernik** [lmfit/lmfit-py#250]
I have been using lmfit with python3 for some 3 years without problems. Recently I had to upgrade from lmfit-0.7.2 to the latest github version (sha: 800f3e) due to obsolete scipy.optimize.anneal (I have scipy 0.16.0). From that point I run into a problems with stderr. Here's a complete example

```
from lmfit import minimize, Parameters, report_errors, report_fit

def fit_func(params, x):
    a0 = params['a0'].value
    a1 = params['a1'].value
    return a0 + a1 * x

def residual(params, x, y, dy):
    model = fit_func(params, x)
    return (y - model) / dy

params = Parameters()
params.add('a0', value=0.0)
params.add('a1', value=1.0)

x = [0, 1, 2, 3]
y = [1, 2.1, 2.9, 3.8]
dy = [0.1, 0.2, 0.3, 0.4]

result = minimize(residual, params, args=(x, y, dy))
report_fit(result.params)

for key, par in result.params.items():
    print('{} {:.3f} +/- {}'.format(key, par.value, par.stderr))

print(params['a0'].stderr)
print(params['a1'].stderr)
```
And the result:
```
[[Variables]]
    a0:   1.00097561 +/- 0        (0.00%) (init= 0)
    a1:   1.00000001 +/- 0        (0.00%) (init= 1)
[[Correlations]] (unreported correlations are <  0.100)
a0 1.001 +/- 0
a1 1.000 +/- 0
None
None
```
Notice that params['a0'].stderr is None. Previously this code would give proper results with errors. I use python 3.4.3.

**Comment by newville** [comment]
@kmiernik  I believe this is NOT related to Python 3, but to using lists instead of arrays as part of the "extra arguments" to the residual function.   That is, if you change

```python
x  = [0, 1, 2, 3]
```

to 

```python
x  = np.array([0, 1, 2, 3])   # after import numpy as np!
```

the fit should work fine for you (it does for me).    It's a little weird that the  `a0 + a1 * x` in `fit_func()`  doesn't throw a TypeError of "can't muliply sequence by non-int of type 'float'" (which you get if just calling `fit_func()`.   Perhaps that is part of the wrapping scipy.optimize does of the user objective function...

I'm also not sure how easy it is for us to auto-convert a list to an array when it is actually "extra" data passed to the objective function.  That is, it's not necessarily the case that every list would be used as an array.  I think it would be nice to avoid such problems, but I'm not entirely sure  how to do so.

The workaround is easy, and has the advantage of being precise in the data types you're using.

**Comment by kmiernik** [comment]
You are absolutely right. I have simplified my example too much. In fact I always keep data within the numpy arrays. But this helped me to actually get to real point of my trouble. I have couple dozens  programs where I use lm_fit, and all of them stopped working...

 As in the example above the last two lines are still showing 'None'. It used to be that the Parameters object was passed by reference and updated outside the minimize function. Now it looks like there is a copy of this object in result.params and this is where the results are, while the Parameters are still showing the initial conditions. Was this change deliberate? Most of my script do not return result.params and rely on passing by reference, so I have some serious rewriting ahead of me.

**Comment by newville** [comment]
@kmiernik 

> You are absolutely right. I have simplified my example too much. In fact I always keep data within the numpy arrays. But this helped me to actually get to real point of my trouble

Ah, there were *two* *separate* issues then, neither of which were related to Python3.   Sorry for not understanding.   

I don't mean to pick on you, but please allow me take this opportunity to remind everyone that starting a conversation with "I found a problem with XXX" (in this case XXX=stderr) is much more likely to cause needless confusion and extra work than starting the conversation with a question of "why did this thing happen that I didn't expect to happen"?     For example, though the title implies Python3 is part of the issue, all this behavior is independent of Python version.  And what you really wanted to know was why  `params.stderr = None` (which I do not see as a "problem"), not why the reported `stderr` was 0 (which *is* a problem).   So, in posing this as an Issue, you first asserted an assumption that turned out to be not relevant, presented a problem you did not intend, and presented as a problem something that is not actually a problem.    It's all OK, we can figure this problem out, but it involves more effort than needed.

So, please use the mailing list to ask questions *before* raising an issue.    The instructions at 
https://github.com/lmfit/lmfit-py/blob/master/Contributing.md (which everyone submitting an Issue is supposed to read before submitting an Issue) is sort of clear on this.   The fact that I keep saying this in Issues conversations definitely suggests to me that people submitting new issues are not reading old issues or the instructions.  Which is one of the reasons why a mailing list is better.

> I have couple dozens programs where I use lm_fit, and all of them stopped working...
>
> As in the example above the last two lines are still showing 'None'. It used to be that the Parameters object was passed by reference and updated outside the minimize function. Now it looks like there is a copy of this object in result.params and this is where the results are, while the Parameters are still showing the initial conditions. Was this change deliberate? Most of my script do not return result.params and rely on passing by reference, so I have some serious rewriting ahead of me.

Yes, this is a feature in the latest version (github master). It's been discussed several times.   See #230, #197, #183, and #174.

This version  **absolutely does** break all scripts that worked with 0.8.3, in a way that is not backwards compatible.   Yes, all scripts will have to be changed in a way that is small, but necessary.

In the new version, the `params` you pass in are **NOT** altered by the fit.  A copy of your input `params` is made, this copy is varied in the fit and is returned to you as `result.params`.     In fact, in your script you have

```python
result = minimize(residual, params, args=(x, y, dy))
report_fit(result.params)    # recommendation:  report_fit(result)
```

which is correct and should show actual uncertainties for the parameters.  In fact, this is part of what threw me off -- you're using the new form and the report said `stderr` was 0, not `None`, and `params['a0'].stderr` should be `None`.   

Anyway, hope that helps.

**Comment by kmiernik** [comment]
Thanks for the help and sorry for confusion. Should I knew before where is the real problem I would probably solved it by myself. My fault in not digging deep enough and taking the weird results for a bug. But as you see the problem is somehow confusing because of inconsistency of behaviour of fit_func() (no TypeError) and report_fit() (0 instead of None). As the saying goes: a problem well-defined is half solved.

The #230 which actually answers everything is a closed pull request. It is not that easy to find, wouldn't you agree? I've looked through the open issues only, which is a normal thing to do. Perhaps the contribution instruction should always require to post a problem on mailing list and only if it happens to be a bug not a feature to be moved to github.

**Comment by newville** [comment]
On Fri, Sep 4, 2015 at 11:03 AM, Krzysztof Miernik <notifications@github.com
> wrote:

> Thanks for the help and sorry for confusion. Should I knew before where is
> the real problem I would probably solved it by myself. My fault in not
> digging deep enough and taking the weird results for a bug. But as you see
> the problem is somehow confusing because of inconsistency of behaviour of
> fit_func() (no TypeError) and report_fit() (0 instead of None). As the
> saying goes: a problem well-defined is half solved.
>

Oh, well, we definitely broke stuff  between 0.8.3 and the current master
branch. So it's completely understandable that people will be confused
about this for a while...  Suggestions on how to document the changed
behavior would be most welcome!

> The #230 <https://github.com/lmfit/lmfit-py/pull/230> which actually
> answers everything is a closed pull request. It is not that easy to find,
> wouldn't you agree?
>

I do agree.

> I've looked through the open issues only, which is a normal thing to do.
> Perhaps the contribution instruction should always require to post a
> problem on mailing list and only if it happens to be a bug not a feature to
> be moved to github.
>

I completely understand and agree.


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lmfit/lmfit-py/issues/250#issuecomment-137777614>.
>



-- 
--Matt Newville <newville at cars.uchicago.edu> 630-252-0431
