### ISSUE TITLE
ExpressionModel: prefix argument does nothing

### ISSUE THREAD

**Issue by kielpins-hp** [lmfit/lmfit-py#256]
When I create an ExpressionModel using the 'prefix' keyword argument, the parameters of the model are just the same as if I did not use the 'prefix' argument. The 'prefix' argument works fine for built-in models. 

Minimal code example:

    import lmfit.models

    prefix = 'this_'
    expr_mod = lmfit.models.ExpressionModel('c * x', prefix=prefix)
    for expr_pname in expr_mod.param_names:
        print 'ExpressionModel parameter:', expr_pname
    
    const_mod = lmfit.models.ConstantModel(prefix=prefix)
    for const_pname in const_mod.param_names:
        print 'ConstantModel parameter:', const_pname

produces the output

    ExpressionModel parameter: c         # unexpected!
    ConstantModel parameter: this_c    # normal

**Comment by newville** [comment]
@kielpins-hp My inclination would be to consider this a documentation issue, and perhaps give a Warning if `prefix` is used with `ExpressionModel`, but to not change the actual behavior.

The prefix is necessary to avoid parameter name collisions for composite models built from existing models. Like, lots of models have parameters named 'amplitude', 'sigma', and 'center'.   But you chose the names of the parameters for an `ExpressionModel`.   If it's not necessary (and it would complicate the implementation), what's the benefit?

I'm willing to be persuaded.  What's the use-case?

**Comment by kielpins-hp** [comment]
Thanks Matt. A Warning and/or mention in documentation would have saved me some time. There is, of course, a workaround by defining a function and using it to create a normal `Model`. 

In my case, I had to model a sum of amplitude-modulated sinusoids, so it appeared convenient to make `ExpressionModel`s in a `for` loop and sum them.

Thanks for this great package - I am using it heavily and find that it does essentially everything I could want.

**Comment by newville** [comment]
@patquem ExpressionModel does not support `prefix`.  There is no plan to change that -- it would be a rather challenging problem to try to solve.

But also, ExpressionModel is meant to support Models from user input - it's kind of an interesting "hack".  For sure, it is very limiting simply because it allows only one expression for the model function.

If you are modeling several peaks in a compound Model, can you not write an actual Model function and then use that?  We have many built-in lineshapes that are 1- to 3-lines of code, but write them as Python functions so that a) the mapping of function arguments to Parameter names is more obvious, b) the model function can be tested independently, and c) the full range of Model options is supported, including using prefixes to build composite functions.   An ExpressionModel does not allow any of those.  

> Without prefix associated with the param_names of the ExpressionModel, how could it be possible?

Write a model function.  If you already have the ExpressionModel, that should be easy.

**Comment by patquem** [comment]
Thank you very much @newville for the response and sorry for the delayed reply. 

FYI, I have developed a spectral decomposition tool based on lmfit and called **[Fitspy](https://github.com/CEA-MetroCarac/fitspy)** in which I found interesting to provide to the users the ability to specify their own model (either through Python scripts or, more simply, through literal expressions interpreted by ExpressionModel - see [here](https://cea-metrocarac.github.io/fitspy/doc/user_guide/peak_models.html#user-defined-models)). 
Since these are user-defined models, I do not have any a priori knowledge of what these models could be. 

About the 'prefix' limitation and regarding your response, I must admit that I do not quite understand when you say _'it would be a rather challenging problem to try to solve_.' 
Indeed, with the following work-around described below all seems to work very well in my case (composite models using various ExpressionModels) :
```
  model = ExpressionModel(expr, independent_vars=['x'])
  model.make_params()
  param_names = model.param_names.copy()
  model.prefix = prefix  # -> make model.param_names = []
  for name in param_names:
       model.param_names.append(prefix + name)  # -> reassign model.param_names with prefix
```
To be honest, I do not see very clearly why the 'no-prefix' restriction have been imposed for ExpressionModel (???).

_(Regardless, thank you very much for the lmfit library and the support you provide in the issues)_
