### ISSUE TITLE
Dangerous to set param_hints directly

### ISSUE THREAD

**Issue by kielpins-hp** [lmfit/lmfit-py#273]
According to the docs, one can set Model.param_hints directly.
http://lmfit.github.io/lmfit-py/model.html#using-parameter-hints

This appears to be dangerous in at least one case. LorentzianModel.__init__() sets an essential parameter hint for 'fwhm':

    self.set_param_hint('fwhm', expr=fwhm_expr(self))

Without this hint, I find that LorentzianModel.fit() returns NaNs, for instance in best_values. So blindly overwriting param_hints and subsequently generating parameters with make_params() will result in a model that cannot be fitted.

**Comment by newville** [comment]
@kielpins-hp  As always, providing a small script that demonstrates the Issue being raised would be greatle appreciated.  Otherwise, this appears very similar to part of the conversation for #271, but I can't exactly tell what the new issue here is.   

Yes, parameter hints can be "dangerous", and should be used with caution.  And yes, many of the built-in models use parameter hints.    Is that a problem? The in-progress PR #270 may change some of this.   With that branch,  this: 

```python
mod = LorentzianModel()
mod.param_hints = {}
pars = mod.make_params()
out = mod.fit(y, x=x)
```
does not give an error, the fit works, and there is no `fwhm` parameter that would have been set with the default parameter hints.

**Comment by newville** [comment]
No example given.  This is not an Issue.
