### ISSUE TITLE
eps_data not defined in  lmfit-py/doc/intro.rst

### ISSUE THREAD

**Issue by jboulder** [lmfit/lmfit-py#275]
The example code won't run.

**Comment by newville** [comment]
@jboulder uh, what?   `eps_data` is just as "not defined" as `x` and `data` in the examples in the documentation.  There is no example code in intro.rst that would run if `eps_data` were defined. 

You don't give an example of what doesn't run.   You read Contributing.md and you still wrote this as an Issue on github instead of phrasing it as a question to the mailing list.   I am continually mystified by why people do this.  If you have a question, then ask on the mailing list.
