### ISSUE TITLE
Fit failures when min/max are used

### ISSUE THREAD

**Issue by CarpeCimex** [lmfit/lmfit-py#280]
I'm still experiencing fit failures when I use min/max bounds.  My [original issue](https://github.com/lmfit/lmfit-py/issues/278#issuecomment-158919780) arose because some of my input values are very small (like 1e-11) and the lmfit conversion

    internal_value =  sqrt( (user_value +1 - min)**2 -1)

and back was making the fitter think that no progress was being made.

My problem consists of fitting electronic circuit component values to measured impedance data.  I can normalize the component values, frequency, and impedance to reduce this bounds problem in some cases, but it's still there.  My normalization options are constrained, to keep the relationship between components, frequency, and impedance correct, so component value differences even after normalization can still be large (sometimes several orders of magnitude).  In other words, I can't always get all normalized component values near 1.

The result is that sometimes specifying min/max bounds causes fitting to fail or work poorly, and sometimes not.

Is it possible to do the `internal_value` calculation differently for each bounded input value, perhaps by using the nominal (guess) value of the bounded variable instead of 1?  I'm not sure that would do it, but something like that might smoothly limit each variable independently and still allow the variables to differ from one another (and from 1) by large amounts.

**Comment by newville** [comment]
@CarpeCimex as you read in Contributing.md, a small script that demonstrates the problem is always appreciated.  Otherwise, you are forcing us to guess what the problem might be, which is both more work for us and more likely to not be helpful to you.   Also, without the context of a script, we can only be general in our responses, and are not able to give a response like 'what if you change this line to <...>?'.
We can try it this way, but you are deliberately choosing to not tell us everything you know, and still expecting a helpful answer.

> My problem consists of fitting electronic circuit component values to measured impedance data. I can normalize the component values, frequency, and impedance to reduce this bounds problem in some cases, but it's still there. My normalization options are constrained, to keep the relationship between components, frequency, and impedance correct, so component value differences even after
normalization can still be large (sometimes several orders of magnitude). In other words, I can't always get all normalized component values near 1.

Again (as with #278), I don't think you need to get all the Parameters within 1 order of magnitude, but I can believe that parameters spanning 14 orders of magnitude could lead to other numerical instabilities.   

> The result is that sometimes specifying min/max bounds causes fitting to fail or work poorly, and sometimes not.
 
> Is it possible to do the internal_value calculation differently for each bounded input value, perhaps by using the nominal (guess) value of the bounded variable instead of 1? I'm not sure that would do it, but  something like that might smoothly limit each variable independently and still allow the variables to differ from one another (and from 1) by large amounts.

Hm, I doubt it.  The "1" in those formula are to smooth out the values near the limits, so as to avoid a "hard wall".   That is, if you replace "1" with "0", the min-only and max-only bounds are just taking absolute values of the internal value.

Another idea: From the discussion for #278, it seems it seems that with values ~1e.-11, the bounds transformation is causing the initial step in the fit be too small to have an effect.   I forgot to mention that you can change this step size, by specifying 'epsfcn' to the `minimize()` function.  This gets passed to `scipy.optimize.leastsq()`, and sets the step size for computing the numerical derivatives.   I believe the default value for this is ~2e-16, and that the relative step sizes are the sqrt() of this (so 1.5e-8).   I would expect that a value for epsfcn in the range 1.e-5 to 1.e-9 would be fine for almost all real cases,  and probably avoid the problems you're seeing.  

I'd assume that it's reasonable for lmfit to change the default epsfcn of 1.e-9, but that would probably need careful testing.

Well, I hope that helps.   If not, re-read Contributing.md.

**Comment by CarpeCimex** [comment]
@newville -- Sorry, I can see how my generic complaint was not very helpful.  I guess I was hoping to provoke a response like "Of *course!*  We can easily make relative bounds that way which wouldn't care if input variables differ by many orders of magnitude!".  A new version would quickly ensue and you'd be eternally grateful to me for my helpful input.  :-)

I guess it's a little messier than that.  I'm using lmfit buried inside a larger script, but I will take a shot at extracting a test bench to demonstrate what I'm seeing.  I also need to get my script going, so I'm working on a separate bounds method which adds elements to the residuals array which get big when a parameter approaches its boundary.  That should also work, once I settle on an inexpensive function which doesn't present a "hard wall" (similar to your `internal_value` conversion).

**Comment by newville** [comment]
@CarpeCimex   I'm not sure what the problem here actually is.  You opened and closed #278, and this issue seems like a similar problem, except that (for some reason) none of the obvious options of scaling the variable, giving a larger initial value, or explicitly setting `epsfcn` will solve the issue you're now having, and you cannot (or will not) tell us what that problem is....   But if you tried those earlier suggestions and they don't help, I'm not optimistic that playing with the internals of the bounds implementation is going to help.   Sorry I can't be more helpful, but you've given us very little to go on.

**Comment by CarpeCimex** [comment]
@newville -- Still working on this.  It's not that I cannot or will not explain, it's that I have not.  I closed #278 since normalizing my equations seemed to fix the problem, but now I'm not so sure.  I can't arbitrarily scale my values (see OP here), so scaling one component value near unity can result in others far from it.  I want to be able to use all minimizing functions in lmfit, and since `epsfcn` only works with `leastsq` I'm looking for another solution.

In my OP here I was fishing for a quick fix to the lmfit bounds which wouldn't require all values within an order of mag or so of unity.  That didn't happen, so I'm digging deeper.

I will try to get to the bottom of it today, and as I mentioned earlier I will provide a test bench if it looks like I am indeed having problems with lmfit bounds.

**Comment by CarpeCimex** [comment]
I'm closing this for now, since I'm not sure if it's a problem or if I can't work around it.  I'll provide a test case if this crops up again.
