### ISSUE TITLE
Puzzling parameter names in built-in models

### ISSUE THREAD

**Issue by dalito** [lmfit/lmfit-py#284]
At least some of the built-in models (GaussianModel, LorentzianModel, ExponentialGaussianModel,...) have a parameter named "amplitude". However, the correct name would be "area" since the models are formulated with area but not amplitude as parameter. 

Due to this area-based model formulation, the results in http://lmfit.github.io/lmfit-py/builtin_models.html#example-3-fitting-multiple-peaks-and-using-prefixes do not match the expected result documented in the NIST StRD test cases. This deviation made me look for possible reasons.

Maybe the best fix is to have two versions of each model, one area and one amplitude based?

**Comment by newville** [comment]
@dalito 

> At least some of the built-in models (GaussianModel, LorentzianModel, ExponentialGaussianModel,...) have a parameter named "amplitude". However, the correct name would be "area" since the models are formulated with area but not amplitude as parameter. 

A Gaussian and Lorentzian (and many other lineshapes) have unit area.  Using an `amplitude` multiplicative factor gives the amplitude of that lineshape.  It also happens to give the area of that lineshape.    There is no distinction.  We try to follow the best mathematical definition we can find.  For Gaussian and Lorentzian, these are pretty clear. 

> Due to this area-based model formulation, the results in http://lmfit.github.io/lmfit-py/builtin_models.html#example-3-fitting-multiple-peaks-and-using-prefixes do not match the expected result documented in the NIST StRD test cases. This deviation made me look for possible reasons.

The model used in the NIST StRD pages does not use properly normalized Gaussians.  In fact, only three of the eight variable parameters have the same value between the NIST version and the lmfit version (`exp_amplitude`  = `beta_1`, `g1_center` = `beta_4`, `g2_center` = `beta_7`).    Notably, their width parameter is neither sigma nor full-width-half-max.

> Maybe the best fix is to have two versions of each model, one area and one amplitude based? 

The best approach is to use a unit normalized Gaussian.

**Comment by dalito** [comment]
@newville Thanks for your reply.

From my background (chemistry/engineering) I was expecting that amplitude is the same as peak height. Peak height has a different dimension (eg. current) than area (e.g. current*time). That is why I was suggesting to have separate area and amplitude(peak height) based models. [SASfit](http://sasfit.ingobressler.net/manual/Gaussian_or_Normal_Distribution) offers this for example. However, since it is so easy to write your own models with lmfit, it is probably not worth adding several very similar models to lmfit.
 
From your answer, it is not clear to me if you want to change anything in the naming of the parameter (amplitude vs. area), in the doc-strings of the models or in the main documentation (e.g. adding a note that amplitude is not peak height). I can prepare a PR if you indicate what you would like to do.

**Comment by newville** [comment]
@dalito Many of us here work in similar fields, and even with X-ray techniques.  It's not so much that we don't appreciate these differences, but having multiple definitions just to be compatible with some other package (even, say, something meant to be general purpose like Origin or fityk) leads to madness.  We're aiming for internal consistency so that peak shapes can be changed with the same parameter names and meanings (where possible), and using the best definitions we can find.  If we deviate from the definition on wikipedia and mathworld, we're probably going to have to document why.   Peak-like functions are unit-normalized whenever possible, and the definitions are actually documented.

Of course, the problems solved here are mathematical in nature, and units are never implicit.  That's basically true for all numerical work. So the reported parameters like "amplitude", "sigma", and "center" should not connote units themselves:  "x" and "y" (provided by the user) should.

For me, the weirdest thing about SASFit is not so much that it has two different Gaussian definitions but that both of them include an constant.   Their Lorentzian does not have a constant or a scale factor.  Their complementary error function has both.   We're definitely not doing that!

Anyway, yes, if you really want a model that is an improperly scaled Gaussian function plus a constant, you can easily write that yourself.   But the builtin models are going to remain properly scaled and able to be composed into composite models.

**Comment by Tillsten** [comment]
I would really like to see 'amplitude' renamed to area, but that ship sadly set sail long ago.
