### ISSUE TITLE
How to evaluate the fit function at arbitrary values??

### ISSUE THREAD

**Issue by ebauch** [lmfit/lmfit-py#341]
Sorry if this is the wrong place, but I couldn't find an answer. How do I evaluate the output fit function at 
arb. values? In Matlab you can simply run

cfit([4,204, 5, some arb value,...]) 

and it returns the fit function value at these coordinates. Very useful if you want to extrapolate beyond the support. I know I can just setup a new function using the fitted parameters, but I am curious if there is an easy way I am not aware of. 

thx!

**Comment by newville** [comment]
@ebauch  This is not an Issue.  This is a question.  You cannot have possibly raised this Issue without having read both  https://github.com/lmfit/lmfit-py/blob/master/.github/ISSUE_TEMPLATE.md and https://github.com/lmfit/lmfit-py/blob/master/.github/Contributing.md.   And yet you still raised an Issue instead of asking on the mailing list as clearly instructed.    

You are asking us a question about how to use free software.  It is rude to not follow the clear instructions about how and where to ask a question.   We try to be very helpful, as you can see from the answers on the mailing list, stackoverflow, and these issues pages.   Your question, though incomplete and vague, probably has a very simple answer that you could figure out if you even glanced at the documentation, and certainly if you used the  search feature built in to the documentation.

Not an Issue.  Not answering questions using Issues. Closing.

**Comment by ebauch** [comment]
Hi Newville, 

I am very sorry if I offended you in any way. It was not my intention, and I agree that my post is not up to standards, after having read them. 

I have a lot of experience with Mathematica and Matlab, but are new to Python. So coming from there I am still trying to learn all the little things about Python and so far I have been pretty amazed with lmfit. I spent quite some time trying to figure out what I described above: 

I first went through all the examples here 

https://lmfit.github.io/lmfit-py/builtin_models.html

and then checked the command list 

https://lmfit.github.io/lmfit-py/genindex.html

to find what I needed, again without success. Ultimately, I just posted the question above after seeing that other users posted questions of that kind as well. I thought it is relatively self explanatory, but I guess not. Either way, I am sorry I offended you. I wasn’t aware that there is a mailing list (and I wouldn't probably have posted there any ways) and I also didn't see guidelines file.

**Comment by newville** [comment]
@ebauch you absolutely did not offend me.  But you clearly failed to follow the direction and asked a question using github Issues.   The instructions clearly say to not do this, and to use the mailing list instead.  It is simply not believable that you could ask a question with github Issues and not see this.

And yet, now you respond with github Issues again.  You are not understanding how this works.  Do not use github issues unless you are raising an issue.  Period. 

If you actually want help, use the proper channels.  Stop using github Issues to ask questions or apologize for using github Issues.  

If you ask a question on the mailing list, it will be answered.  If you use github Issues again, it will not. Clear?
