### ISSUE TITLE
Speed issue in v0.9.5:  lmfit 5 time slower than curve_fit

### ISSUE THREAD

**Issue by pico89** [lmfit/lmfit-py#375]
Hi!

First of all congratulation for this project and thank you very much for your work. I found it very useful and I start the porting of part of my code in order to use it, because it greatly simplify my work.

I than start making some test, and I found out that when I have to make lots of fits (normally I got a 2D map and I have to make a fit for each line of the map for several map, resulting in hundreds or thousands of fit to perform), the process is much slower than doing the same with curve_fit, at the point to prevent me to use lmfit in this case scenario.

I think the problem is related to the issuses #259 and #261, but I didn't dig much in the code. Sorry my python knowledge is pretty poor at the moment.
I tried to reproduce it, using a simple example from the documentation of lmfit, here the code that I used:

```
import timeit

NUMBER = 1000

print(timeit.timeit('''

from numpy import sqrt, pi, exp, linspace
import numpy as np
from scipy.optimize import curve_fit

def gaussian(x, amp, cen, wid):
	"1-d gaussian: gaussian(x, amp, cen, wid)"
	return (amp/(sqrt(2*pi)*wid)) * exp(-(x-cen)**2 /(2*wid**2))

x = linspace(-10,10)
y = gaussian(x, 2.33, 0.21, 1.51) + np.random.normal(0, 0.2, len(x))

init_vals = [1, 0, 1] # for [amp, cen, wid]

best_vals, covar = curve_fit(gaussian, x, y, p0=init_vals)

''', number=NUMBER))
#print best_vals


print(timeit.timeit('''


from numpy import sqrt, pi, exp, linspace
import numpy as np
from lmfit import Model

def gaussian(x, amp, cen, wid):
	"1-d gaussian: gaussian(x, amp, cen, wid)"
	return (amp/(sqrt(2*pi)*wid)) * exp(-(x-cen)**2 /(2*wid**2))

x = linspace(-10,10)
y = gaussian(x, 2.33, 0.21, 1.51) + np.random.normal(0, 0.2, len(x))

gmod = Model(gaussian)
result = gmod.fit(y, x=x, amp=1, cen=0, wid=1)

''', number=NUMBER))
#print(result.fit_report())
```

Running this with NUMBER=1000, it normally takes around 1s for curve_fit, and around 5s to lmfit to run on my notebook. If a use NUMBER=5000, I get 4s vs 20s.

I tried to keep it simple and I hope I din't make any noob error.
If there are no mistakes in my code and you confirm the problem, I hope you will be able to fix it, because I would really like to be able to use more this nice library.

Thank you very much for your help!

**Comment by newville** [comment]
@pico89 Is this related to https://groups.google.com/forum/#!topic/lmfit-py/8_Tzt0mf-uM ?
I don't see why this is related to #259.  What makes you think it is?

Generally speaking, performance is one priority for lmfit, but not the only one.  There may be ways to speed up lmfit, but even if we find such ways we might choose to not implement them.  For example, my guess is that Parameter, and it's 'value' property account for much of the difference here.  But, we *want* a 'value' property.  

If speed is the paramount consideration, and your problem is as simple as your example,  you may not want to use lmfit.  You may not want to use Python for that matter. 

Suggestion or PRs to speed up the calculations welcome!

**Comment by pico89** [comment]
@newville Thank you very much for your quick reply. Sorry I missed the post on google gruops, thanks for the suggestion, they maybe related.

Going through the documentation, I read that both lmfit and curve_fit are wrapper around scipy.optimize.leastsq. Given that I wasn't expecting that much of a difference in performance; #259 seems to me a similar problem in the sense of being something more related to the implementation of the wrapper than to the actual fit process.

I bump into lmfit looking for something that allows me to put constrains on the fit parameters. My example was using simple code from the lmfit documentation in order to prevent any other source of mistakes. 
Usually I have to fit lorentzian peak or sum of lorentzian peaks, so nothing exotic at all, but having signals that cover several order of magnitude, properly fitting the wings of the curve can be really challenging without constrains. For this use case scenario (few tens or hundreds of fit) lmfit is great, allowing me to simplify the code, to combine different model (if I have to make a convolution for example) and to get much more information from the result.

The case of the 2D map I was speaking about in the previous post is a bit different: at the moment it is mainly gaussian fit and I can easily solve it using curve_fit (the last version also implement the possibility to use constrains on the parameters); but it will soon become much more complex and the information and modularity provided by lmfit could be really useful. It just doesn't scale fast enough for my need at the moment.

Of course I do not expect that all the features provided come with no computational cost, but if it is really 4 or 5 times slower, I would suspect there is something else going on (but this is just my non-expert opinion).
I am sorry that I cannot be more helpful at the moment, I will try to provide some more practical example and to dig a bit in the code if I can.

Thank you anyway for your effort.

**Comment by newville** [comment]
On Mon, Nov 21, 2016 at 4:47 PM, pico89 <notifications@github.com> wrote:

> @newville <https://github.com/newville> Thank you very much for your
> quick reply. Sorry I missed the post on google gruops, thanks for the
> suggestion, they maybe related.
>
Really?  That would be an amazing coincidence.

> Going through the documentation, I read that both lmfit and curve_fit are
> wrapper around scipy.optimize.leastsq. Given that I wasn't expecting that
> much of a difference in performance; #259
> <https://github.com/lmfit/lmfit-py/issues/259> seems to me a similar
> problem in the sense of being something more related to the implementation
> of the wrapper than to the actual fit process.
>
I think that you are referring to #259 because it looks to be approximately
the same topic ("too slow"), not because you have any evidence that they
are actually related.  For sure, the wrapping and use of Parameter objects
is likely the biggest difference between curve_fit() and lmfit, but whether
the issue in #259 is relevant here is not obvious to me.


> I bump into lmfit looking for something that allows me to put constrains
> on the fit parameters. My example was using simple code from the lmfit
> documentation in order to prevent any other source of mistakes.
> Usually I have to fit lorentzian peak or sum of lorentzian peaks, so
> nothing exotic at all, but having signals that cover several order of
> magnitude, properly fitting the wings of the curve can be really
> challenging without constrains. For this use case scenario (few tens or
> hundreds of fit) lmfit is great, allowing me to simplify the code, to
> combine different model (if I have to make a convolution for example) and
> to get much more information from the result.
>
> The case of the 2D map I was speaking about in the previous post is a bit
> different: at the moment it is mainly gaussian fit and I can easily solve
> it using curve_fit (the last version also implement the possibility to use
> constrains on the parameters); but it will soon become much more complex
> and the information and modularity provided by lmfit could be really
> useful. It just doesn't scale fast enough for my need at the moment.
>
Well, if curve_fit() fits your needs, by all means use it.  If lmfit
doesn't fit your needs don't use it.  If you want to use lmfit but it is
too slow, look into how to make it faster.

I'm afraid that "Lmfit is too slow" isn't really a very compelling issue.
We're not opposed to making it faster, but speed is not the only goal.
Seriously, we are using Python to do fits to numerical data -- no matter
how fast you try to make it, it will *always* be slow compared to other
solutions.  Then again, raw speed is generally overrated compared to lots
of other features. The most cost-effective response to "it needs to go five
time faster" might be "re-code it in Fortran", but it might also be "buy 4
more machines".

> Of course I do not expect that all the features provided come with no
> computational cost, but if it is really 4 or 5 times slower, I would
> suspect there is something else going on (but this is just my non-expert
> opinion).
>
There is definitely something else going on.  Whether that something else
can be made faster is an open question.

> I am sorry that I cannot be more helpful at the moment, I will try to
> provide some more practical example and to dig a bit in the code if I can.
>

**Comment by Tillsten** [comment]
Just 2 cents:

When profiling with timeit separate the actual computation from the setup. E.g. `timeit(code_to_bench, setup_code)`. Things like import can dominate benchmarks easily. Sadly imports are not the reason for this issue. Two issues are contributing: your actual fitting problem is very easy and small, so the overhead of lmfit making the function call is relative big. Secondly, profiling shows that for such small problems the overhead of instancing the ModelResult and it's Parameters are almost 30% of the running time.

**Comment by newville** [comment]
@Tillsten Thanks and great to hear from you. 

It's completely possible that careful profiling analysis will show some place where performance can be improved.  I think we  (well, really @andyfaff) have looked fairly carefully, but maybe something has been missed. I would encourage @pico89 to look into this.

**Comment by imoric** [comment]
Would it be possible to implement some kind of multithread possibility inside lmfit to increase speed? Would like to use it in particle physics, but at this moment the performance is not there.

**Comment by newville** [comment]
@imoric I think we'd all be very happy to see a speed-up.  But, I sort of doubt that multi-threading would actually help. It is more likely that multi-processing could help for some problems, but I'm afraid I've never seen a real case where it helps.

I would happily be proven wrong on this, but I believe that for any "real" long-runnig problem (that is, not a toy fit that runs in under a few seconds) that the vast majority of the time will be spent in the objective function or in the underlying Fortran code.   If that belief is right, then the solution is probably best done within scipy.optimize.  Long ago I put in a PR to scipy (https://github.com/scipy/scipy/pull/3192) that tried to evaluate the objective function using Nvarys processes, 1 for each update in each fit iteration.   That PR is now far out of date, and it's not without problems (it might really want to use the `dill` package instead of `pickle`), but it may be worth trying that sort of solution again.  Or perhaps there's an even better approach.....

**Comment by newville** [comment]
closing this as it's a vague issue and I think there is not anything we really can do about it.....

**Comment by agoose77** [comment]
I know this issue is closed but I wanted to add a comment RE speed - fitting Gaussians is very slow if you fit using `p0 / (sigma * sqrt(pi*2)) * exp(...)`. This is probably due to blow-up at small sigma, or perhaps the additional dependency on sigma (I am not an expert). If you just fit `p0 * exp(...)` and subsequently determine `p0/(...)` it's *far, far* quicker!
