### ISSUE TITLE
minimum required scipy version and testing against it

### ISSUE THREAD

**Issue by reneeotten** [lmfit/lmfit-py#398]
The `requirements.txt` contains the minimum required versions of numpy/scipy:

```
numpy>=1.5
scipy>=0.14
```
on the other hand, the `__init__.py` will print `__main__:2: UserWarning: Support for Scipy 0.14 was dropped with lmfit 0.9.5` when the installed scipy version is lower than 0.15. To me that reads as if version 0.15 is actually the minimum required version, or...? Given the fact that scipy 0.15 is already more than 2 years old, I would assume that almost everyone is using a more recent version of scipy already anyway - is  there a specific reason to be compatible with such old versions?

Requiring version 0.15 or higher would have the benefit that scipy actually contains `differential_evolution` and would allow lmfit to just call `scipy.optimize.differential_evolution` instead of calling it through `scalar_minimize`. In addition, there would be no need anymore to distribute/maintain a separate `_differentialevolution.py` file that essentially contains the same code.

Either way, whatever decision is made on the minimum required versions, I think it should be these same version that are used for the Travis CI testing. Currently, when creating the conda environment is just installs the most recent versions of numpy/scipy.

**Comment by newville** [comment]
@reneerotten. OK, you've convinced me that having a hard requirement for scipy 0.15 (and so dropping our own version of diffev code) is appropriate for 0.9.6.  I think we should let @andyfaff make the final decision.
Also, I agree with the testing against specific versions (especially scipy for sure too.

**Comment by andyfaff** [comment]
I'd welcome a transition to 0.15 for scipy. W.r.t to removing the diffev
code from lmfit, I'd prefer if that was done in a separate PR.

On 23 Feb 2017 6:06 am, "Matt Newville" <notifications@github.com> wrote:

@reneerotten. OK, you've convinced me that having a hard requirement for
scipy 0.15 (and so dropping our own version of diffev code) is appropriate
for 0.9.6. I think we should let @andyfaff <https://github.com/andyfaff>
make the final decision.
Also, I agree with the testing against specific versions (especially scipy
for sure too.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/lmfit/lmfit-py/issues/398#issuecomment-281768686>, or mute
the thread

**Comment by newville** [comment]
@andyfaff Thanks.  I agree on a separate PR to require 0.15, removing the soon-to-be unneeded code.  Preferably with doc change.

Any volunteers?

**Comment by reneeotten** [comment]
@newville @andyfaff I will give it a go and split it in two PRs: (i) bumping the scipy version to 0.15 and updating `.travis.yml` and (ii) removing the diffev code. What are your thoughts about a reasonable minimum numpy version, the current requirement (1.5) is also kind of pre-historic, or...?

**Comment by newville** [comment]
Fixed with merge of #399
