### ISSUE TITLE
dimension check failed using user defined jacobian

### ISSUE THREAD

**Issue by luminoctum** [lmfit/lmfit-py#42]
Hi there,

Thanks for the wonderful code! I've experiencing difficulty using user defined jacobian. Suppose I have m data points and n state variables. I calculated the jacobian myself and returned a matrix of shape (m, n). It works well for leastsq but failed typecheck in lmfit. Is there any possible way to fix this issue?

Cheng

**Comment by Andrea-gm** [comment]
Hello. I was wondering if there has been any change to the way the Jacobian is handled by Minimizer since this discussion?

**Comment by newville** [comment]
@Andrea-gm This issue was closed more than 10 years ago. 

"Any change"?  I am not sure that I can say there were "no changes" in the past ten years, though I see no other Issues, Pull Requests, or Discussions reference this.  If the question is really "Did the code change?", check the git history. 

If you have an actionable question about existing code, please use the mailing list or Github Discussions.

**Comment by Andrea-gm** [comment]
@newville Thanks for the quick reply Matt. Given that I cannot find any information about this in the docs, I was just wandering if lmfit still passes only the independent variables, as you explained in your comment on October 26th, or whether you implemented any of the changes suggested in the following comments. If such changes have been made, is there anywhere I can find information on it?

**Comment by newville** [comment]
@Andrea-gm This issue was closed more than 10 years ago.  
If you have a question about the current code, use the mailing list or Github Discussions.
