### ISSUE TITLE
Not able to run minimize() or Model.fit() in multiprocessing

### ISSUE THREAD

**Issue by parfa30** [lmfit/lmfit-py#469]
I have tried to run Model.fit() and minimize(residual_function) within a function that I am using with multiprocessing.pool. All other Model functions seem to have no problem (i.e. Model.eval()) but the code seems to ignore the fit function completely, meaning there is no failure, error message, etc. 

From reading another comment here it sounds like this should have something to do with pickling of the input. Any experience with this or any advice?

**Comment by newville** [comment]
@parfa30  You must have read https://github.com/lmfit/lmfit-py/blob/master/.github/ISSUE_TEMPLATE.md and https://github.com/lmfit/lmfit-py/blob/master/.github/CONTRIBUTING.md in order to raise this as a Github Issue.   And yet you chose to ignore the instructions there to post questions to the mailing list and posted your question as an Issue here.  You include no code and show no messages from running your code as anyone posting a real issue would.

The instructions are pretty clear and impossible to miss.   You cannot claim anything except that you deliberately ignored them.  We all try to be as helpful as possible, and help lots of people with lots of different questions about various free software for scientific work.  Speaking only for myself, I do not feel compelled or obligated to help rude people.
