### ISSUE TITLE
func method for StepModel only return linear form

### ISSUE THREAD

**Issue by gmonet** [lmfit/lmfit-py#555]
#### Description
When I try to use func method for StepModel it returns linear form step even if I create arctan step model.

###### A Minimal, Complete, and Verifiable example
```
import numpy as np
import matplotlib.pyplot as plt
from lmfit.models import GaussianModel
x = np.arange(-10,10,0.01)
g = GaussianModel()
plt.plot(x, g.func(x))
plt.plot(x, g.eval(x=x))
```
![image](https://user-images.githubusercontent.com/12810242/57872841-e8ab6c80-780c-11e9-97fa-34ff601687e0.png)
Working :)

```
import numpy as np
import matplotlib.pyplot as plt
from lmfit.models import StepModel
x = np.arange(-10,10,0.01)
s = StepModel(form='arctan')
plt.plot(x, s.func(x))
plt.plot(x, s.eval(x=x))
```
![image](https://user-images.githubusercontent.com/12810242/57872820-daf5e700-780c-11e9-9067-e45373d8d282.png)
Not Working :(

###### Version information
Python: 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
lmfit: 0.9.12, scipy: 1.2.1, numpy: 1.16.2, asteval: 0.9.13, uncertainties: 3.0.3, six: 1.12.0

**Comment by newville** [comment]
@gmonet  Oh, hmm,  I don't know what's going on, but I'll look in to it. Thanks!

**Comment by newville** [comment]
@gmonet  Actually, on second look, I don't see this as a problem.  

When you call `StepModel.func()` with only `x` as a parameter, that is directly calling `lmfit.lineshapes.step()`.  Since you are not specifying any other function arguments, it is using its default parameters of amplitude=1, center=0, sigma=1, form='linear'.    

You almost certainly don't want to use `StepModel.func` anyway, you *want* to use `StepModel.eval()`, pretty much for exactly the differences you report.  The `eval` method knows to use the other attributes of the instance of StepModel, while `func` is just a (dumb) reference to the underlying model function.

**Comment by gmonet** [comment]
@newville Ok, i see !
```
import numpy as np
import matplotlib.pyplot as plt
from lmfit.models import StepModel
x = np.arange(-10,10,0.01)
s = StepModel(form='arctan')
plt.plot(x, s.func(x,**s.opts))
plt.plot(x, s.eval(x=x))
```
![image](https://user-images.githubusercontent.com/12810242/57905716-b8e57e80-7877-11e9-9d0f-0a5d4b1dabeb.png)

I understand that it is preferable to use the eval method when using lmfit "normally" but I need to use the func attribute in my case because I would like to give an np.array as a model parameter. Basically, I write a small lmfit top layer to fit several curves at the same time (about 400) with shared parameters. Using expr is to slow/heavy in this case.
Anyway, thank you @newville for your quick answer.
