### ISSUE TITLE
Sending nan_policy inside fit_kws causes exception 

### ISSUE THREAD

**Issue by yoavram** [lmfit/lmfit-py#562]
#### Description
Sending `fit_kws=dict(nan_policy=...)` to `model.fit` used to work before (I think) commit 886dfeffad2fddc7449efedd93ac411009331fe5. This commit added an explicit `nan_policy` keyword argument, which clashes with the implicit keyword argument sent via `fit_kws`.

Of course, I could just update lmfit. But this does break backwards compatibility, which is not supposed to happen in a patch (0.9.x->0.913).

###### A Minimal, Complete, and Verifiable example
```
model.fit(data=y, t=t, params=params, fit_kws=dict(nan_policy='propagate'))
```

###### Error message:

```
...
File "/home/travis/miniconda/envs/travis-env/lib/python3.6/site-packages/lmfit/model.py", line 1006, in fit
    **fit_kws)
TypeError: type object got multiple values for keyword argument 'nan_policy'
```

###### Version information
Works with Lmfit version 0.9.5, fails with version 0.9.13.

**Comment by newville** [comment]
@yoavram 

> Of course, I could just update lmfit. But this does break backwards compatibility, which is not supposed to happen in a patch (0.9.x->0.913).

Nope, that is not a rule we're going to follow.  This is an all-volunteer effort, and there is and will not ever anything we are "supposed" to do.  We are free to add keyword arguments to rationalize and fix problems with the API, as we did (21 months ago!) for this change.  We did deprecate and then remove the `missing` keyword as we added the `nan_policy` keyword. There is a `fit_kws` argument so the API is not altered even if the *contents* of that argument cause problems.

I think the only way this could possibly be "fixed" would be to inspect the contents of `fit_kws`.  If we do go down that path, it might be better to remove `fit_kws` entirely.  That has some appeal, but would be a good amount of work, more or less separating from the scipy.optimize API.   That might be related to the discussion and thoughts about version 1.0 at #544.   To be clear, it's not going to happen soon.

**Comment by reneeotten** [comment]
Just as a follow-up: it might have worked before, but I think is twas was never supposed/intended usage of ```fit_kws```.

The ```fit_kws``` argument is described as "fit_kws (dict, optional) – Options to pass to the minimizer being used", so in this case it should contain only options to pass to ```scipy.leastsq```. And ```nan_policy``` clearly isn't one, but we indeed do not check and make sure that ```fit_kws``` only contains arguments for the downstream fitting algorithm. As @newville says that might be something to look into, but isn't necessarily a quick-and-easy thing to do. 

Finally, you can easily accomplish what you want to do by just supplying ```nan_policy='propate'``` when you initialize your model as described in the manual, instead of when performing the fit.

**Comment by yoavram** [comment]
OK, thanks for the quick and detailed replies!
