### ISSUE TITLE
Error "The input contains nan values"

### ISSUE THREAD

**Issue by SengerM** [lmfit/lmfit-py#580]
Hi,

I think I am facing a bug, sorry if I am missing something stupid and it is not a bug, I have been some time trying to figure out what is happening with no success. 

I am trying to fit a function to some data and am receiving this error. A MWE that generates my error is in [this repository](https://github.com/SengerM/lmfit_error).

Matías.

**Comment by newville** [comment]
@SengerM   We have clear instructions on how to report an issue.  You must have read these and decided to ignore them and even deleted the template for how to structure an Issue.   We expect that anyone using lmfit has some technical and/or programming skill, can read and follow instructions, and understands that all code we produce and any help we give is completely voluntary.   When people like you rudely ignore our instructions, it is demotivating for us to help anyone. 

As it turns out, your question is actually answered in the FAQ.  Indeed basic print statements would probably show you exactly what is causing NaNs to appear in your calculations.   As a hint, I'll remind you of this:

     >>> import numpy as np
     >>> from scipy.stats import norm
     >>> print(norm.cdf(np.linspace(0, 1, 11), loc=2, scale=-1))
     array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

I'm closing this issue and expecting that there will be no follow-up questions.   If you ever have any questions about lmfit in the future, you will have to use the mailing list.
