### ISSUE TITLE
Fits to Models fail for x and y input data with certain datatypes, but not others

### ISSUE THREAD

**Issue by heltluke** [lmfit/lmfit-py#617]
#### Description
Fits using `set_param_hint()`, `make_params()`, and `fit()` appear to fail when the data (y-values) used as input have dtype `numpy.int32` and the x-values used as input have dtype `numpy.int32`. It doesn't appear to fail if both are `numpy.float32` or both `numpy.int32`.

###### A Minimal, Complete, and Verifiable example
```python
import numpy as np
from lmfit import Model

def my_line(x, a, b):
    return a + b * x

def fit_my_line(xs, ys, a_guess, b_guess):
    l_model = Model(my_line)
    l_model.set_param_hint("a", value=a_guess)
    l_model.set_param_hint("b", value=b_guess)
    l_params = l_model.make_params()
    return l_model.fit(ys, l_params, x=xs)

test_xs = np.arange(0,100, dtype=np.float32)
test_ys = np.asarray(test_xs * 2, dtype=np.int32)

print(fit_my_line(test_xs, test_ys, 3, 5).fit_report())
```

###### Error message:
Not exactly an error, but still unexpected: 
```
[[Model]]
    Model(my_line)
[[Fit Statistics]]
    # fitting method   = leastsq
    # function evals   = 3
    # data points      = 100
    # variables        = 2
    chi-square         = 3045150.00
    reduced chi-square = 31072.9592
    Akaike info crit   = 1036.38905
    Bayesian info crit = 1041.59939
##  Warning: uncertainties could not be estimated:
    a:  at initial value
    b:  at initial value
[[Variables]]
    a:  3.00000000 (init = 3)
    b:  5.00000000 (init = 5)
```

###### Version information
```
Python: 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0]

lmfit: 1.0.0, scipy: 1.3.2, numpy: 1.18.1, asteval: 0.9.18, uncertainties: 3.1.2
```

###### Link(s)
None

**Comment by newville** [comment]
@heltluke Yup.  If you had read the FAQ you would have known that the fits work with 64-bit floats:

      The fitting routines accept data arrays that are one-dimensional and double precision.

Please do read the FAQ, and the instructions for raising an issue.

**Comment by lneuhaus** [comment]
I experienced this problem together with @heltluke. Thanks for the quick response, referring to this section if I found right one: https://lmfit.github.io/lmfit-py/faq.html#how-can-i-fit-multi-dimensional-data

I would like to suggest to re-open this ticket as a feature request for automatic type conversion of the input data to 64-bit floats, possibly accompanied by a warning, or (if that change would be against the lmfit philosophy for any reason) raising an exception when inappropriate data is passed. 

The reasons why I think this would be a good solution are
- the FAQ currently does not emphasize the need for double precision floats enough (the comment is hidden in a section I would typically skip if I only had one-dimensional data, and the word "accept" does not handle the case where other data types are passed to the fit)
- raising an exception would be much better than silently failing to fit
- the default numpy array type is float32 on many platforms, so https://lmfit.github.io/lmfit-py/examples/documentation/parameters_valuesdict.html#sphx-glr-examples-documentation-parameters-valuesdict-py doesn't even use doubles, which I consider proof that requiring the user to ensure the input data is 64-bit float is error prone and unrealistic
- automatic handling of the data type seems more pythonic in my opinion

**Comment by newville** [comment]
@lneuhaus  It appears nobody reads the faqs or wants to use the mailing list we set up specifically for such discussions.

We do some data conversions, including multidimensional, complex numpy arrays and Pandas series,  but we do not check if the result of the model function is `float32`.   We deliberately do no type checking on the `x` data:  in `lmfit` the independent variables are not even assumed to be numpy arrays and are simply passed to your model function.

To be clear, in the problem here was the forcing of `test_xs` to have dtype of foat32  (the default for `arange(0, 100)` is int64). Even coercing it to be int32 the fit would work just fine.   The problem is only when `x` is forced to be float32.

So, yeah, I guess we could ensure that the result of the model function is coerced to `float64`.

> the default numpy array type is float32 on many platforms, so https://lmfit.github.io/lmfit-py/examples/documentation/parameters_valuesdict.html#sphx-glr-examples-documentation-parameters-valuesdict-py doesn't even use doubles, which I consider proof that requiring the user to ensure the input data is 64-bit float is error prone and unrealistic

On all systems we test (and use), the example you link to uses doubles (and works, of course).  

Similar to #613, we don't test on 32-bit systems.  No solution for how to do that has been suggested. On systems that use `float32` as default (which platforms are those?  Are they "many"?), float32 may be fine, as the underlying C/Fortran solvers might be built using the same data types.
