### ISSUE TITLE
hint is wrong for lognormal model

### ISSUE THREAD

**Issue by YoshieraHuang** [lmfit/lmfit-py#644]
#### Description
Lognormal model in lmfit use this formula for fitting:
```latex
f(x; A, \mu, \sigma) = \frac{A}{\sigma\sqrt{2\pi}}\frac{e^{-(\ln(x) - \mu)^2/ 2\sigma^2}}{x}
```
I use this model to fit my data but i failed several times to use this model. 

I found that \mu is limited to be positive but \mu should not be limited in math. I think some one is confused with another representation of lognormal function:
```latex
f(x; A, \mu, \sigma) = \frac{A}{\sigma\sqrt{2\pi}}\frac{e^{-(\ln(x) - \ln(\mu))^2/ 2\sigma^2}}{x}
```
where a \ln is applied to \mu and \mu should be limited to be greater than 0.

I set the limit of \mu manually and it works.

I prefer to changing the model to \ln one to fix the bug.

###### Version information
Python: 3.7.3 | packaged by conda-forge | (default, Mar 27 2019, 23:01:00) 
[GCC 7.3.0]

lmfit: 1.0.1, scipy: 1.3.3, numpy: 1.17.4, asteval: 0.9.18, uncertainties: 3.0.3

**Comment by newville** [comment]
@YoshieraHuang Thanks - I think you are correct that `center` should not be limited to positive values here.

I don't have a strong preference for `\ln(x) - \mu` vs `\ln(x) - \ln(\mu)` but I think going with the Wikipedia form is defensible as "consistent with other models" and that changing the hint instead of the functional form would be less disruptive to any existing scripts.

A PR to remove the hint would be welcome. If you are not up for that, let us know and we'll try to get to it soon.
