### ISSUE TITLE
remaining .sav files after tests

### ISSUE THREAD

**Issue by picca** [lmfit/lmfit-py#660]
Hello, I am preparing the 1.0.1 Debian package of lmfit-py

I endup with this error message using our quaslity insurance tools

E: python3-lmfit: unknown-file-in-python-module-directory usr/lib/python3/dist-packages/parameters.sav
E: python3-lmfit: unknown-file-in-python-module-directory usr/lib/python3/dist-packages/tmpvoigt_modelresult.sav

It means that during tests, thes two files were generated under the build path.
It would be nice if you could clean these files once the test done.

thanks for considering

**Comment by newville** [comment]
@picca:  Um, yeah, running tests (or heck, even importing python modules) might generate files on disk.  Why are you using a packaging tool that considers that to be a problem?  If it is a problem for you, don't run the tests or do a clean install.

**Comment by picca** [comment]
> @picca<https://github.com/picca>: Um, yeah, running tests (or heck, even importing python modules) might generate files on disk. Why are you using a packaging tool that considers that to be a problem? If it is a problem for you, don't run the tests or do a clean install.

Hello, I can explain why I am using Debian as OS, but it seems to me out of scope :)

so I want to run the test in order to verify that I have a working lmfit-py.

for the clean install,

I use python setup.py install

**Comment by newville** [comment]
@picca Yeah, using Debian or any other OS or any other packaging system is fine with me.  

But why should we change what we do because some packaging system doesn't like some files being generated in testing?  What if we *want* to test generating files? In fact, we do want to test that.  Generating a package certainly does not require running the tests, but it absolutely, definitely, 100% requires generating files.  So a package manager complaining about generating files seems, um, well, silly.  

Again, I don't care if you think that it will somehow help something to always run tests when building a package (this seems like one of those steps that someone once thought was "best practice" and so became common. But, honestly, I do not know what your package manager would choose to do if a test fails), but why do you expect us to change our tests to meet the artificial standards that you claim that your package manager has?  Our tests generate files. Your package manager should accept that.
