### ISSUE TITLE
failed tests/test_model.py::TestUserDefiniedModel::test_composite_plotting

### ISSUE THREAD

**Issue by spalato** [lmfit/lmfit-py#712]
Hi all,

This is my first issue here. Yes, I read the instructions and I am sure this is a GitHub Issue.

I just forked the repo, created a clean conda env, installed the dependencies (using `pip`), and ran `py.test`. I got a single failing test. 

Output of `py.test --lf --tb=short`:
```
tests\test_model.py:792: in test_composite_plotting
    fig, ax = result.plot(show_init=True)
E   TypeError: cannot unpack non-iterable NoneType object
```

Somehow the guarded import at line 39 in `lmfit.model` fails to import `matplotlib`, yet the `pytest.importorskip("matplotlib")` (and ensuing `import matplotlib`) succeeds. (Direct `import matplotlib` statements also work..). The `_ensureMatplotlib` decorator causes `result.plot` to return `None`.

The specific import error around line 39 of `lmfit.model` is:
```
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
```

Running `pip install pycairo` fixes the issue. Adding `pycairo` to the list of requirements would likely fix this issue.

For completeness, here is version info:
```python
>>> import sys, lmfit, numpy, scipy, asteval, uncertainties, six
>>> print('Python: {}\n\nlmfit: {}, scipy: {}, numpy: {}, asteval: {}, uncertainties: {}, six: {}'\
...       .format(sys.version, lmfit.__version__, scipy.__version__, numpy.__version__, \
...       asteval.__version__, uncertainties.__version__, six.__version__))
Python: 3.9.1 | packaged by conda-forge | (default, Jan 26 2021, 01:29:07) [MSC v.1916 64 bit (AMD64)]

lmfit: 1.0.2, scipy: 1.6.1, numpy: 1.20.1, asteval: 0.9.22, uncertainties: 3.1.5, six: 1.15.0
```
I got the same error using the latest commit on `master`.

**Comment by reneeotten** [comment]
this must be somehow related to your specific installation I think, since we don't see this error on Azure (i.e., Linux) nor do I locally (on macOS). Am I correct that you are using Windows? I think you are trying to use a backend, but haven't installed the correct packages for it. That, is if you're using the `cairo` backend then you should have of course the `pycairo` package installed. However, this isn't something we/lmfit has to declare, but it should be installed by matplotlib if you use that backend. I am not sure there is anything we can do about this.... but let's see if we can figure something out:

- what version of `matplotlib` do you have installed? Do `import matplotlib` and `import matplotlib.pyplot as plt` work. 
- do you see the same issue if you run `doc_model_gaussian.py` in the `examples` directory? 
Please, first do `python -i -i doc_model_gaussian.py`, that should give you a plot. Then type `result.plot()` on the Python prompt and see if that works as well.

**Comment by reneeotten** [comment]
@spalato actually, it looks like you have Python installed through `conda`. However, you say that you installed dependencies using `pip`; that might be the issue here. I would not recommend mixing/matching `conda` and `pip`. 

Can you try the following:
- create new conda environment
- install the dependencies, at least: `conda install asteval numpy scipy uncertainties` as the minimum ones or all of the ones listed in `requirements-dev.txt`. 
- then you can do `python setup.py install` from the lmfit source directory or take the latest version available on conda with `conda install -c conda-forge lmfit`. 

I am pretty sure that will work.

**Comment by newville** [comment]
FWIW, I think it should be fine to install pure python modules like `lmfit` with pip.  I also recognize that I am in the minority on this view.   I use Anaconda Python and maintain some conda recipes.  Both are overrated. 

We should **not** add `pycairo` as a dependency for `lmfit`.  `matplotlib` is not even a dependency.  

I don't understand why this test is ailing for @spalato.  Perhaps something changed with `Agg` backend to require cairo as a dependency? (that's a wild guess).   We *could* check that `result.plot(show_init=True)` has not returned `None` before assuming it can be unpacked to `fig, ax`, since maybe that call to `plot` fails if the `Agg` backend cannot be used.

My biggest regret with `lmfit` is agreeing to add `Model.plot`.

**Comment by spalato** [comment]
> I think it should be fine to install pure python modules like `lmfit` with `pip`. 

I think so too. (Can one manage the `python` version using `pip`?)
To avoid problems, I ran:
`conda create -n lmfit_dev python pip`, `pip install --no-cache -r ./requirements-dev.txt` and `pip install -e .`.


> * what version of `matplotlib` do you have installed? Do `import matplotlib` and `import matplotlib.pyplot as plt` work.

Surprisingly, the answers are: yes and no.

```
>>> import matplotlib
>>> matplotlib.__version__
'3.3.4'
>>> import matplotlib.pyplot as plt
Traceback (most recent call last):
  File "C:\Users\samue\Anaconda3\envs\lmfit_cairo\lib\site-packages\matplotlib\backends\backend_cairo.py", line 15, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\samue\Anaconda3\envs\lmfit_cairo\lib\site-packages\matplotlib\pyplot.py", line 2336, in <module>
    switch_backend(rcParams["backend"])
  File "C:\Users\samue\Anaconda3\envs\lmfit_cairo\lib\site-packages\matplotlib\__init__.py", line 703, in __getitem__
    plt.switch_backend(rcsetup._auto_backend_sentinel)
  File "C:\Users\samue\Anaconda3\envs\lmfit_cairo\lib\site-packages\matplotlib\pyplot.py", line 256, in switch_backend
    switch_backend(candidate)
  File "C:\Users\samue\Anaconda3\envs\lmfit_cairo\lib\site-packages\matplotlib\pyplot.py", line 276, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File "C:\Users\samue\Anaconda3\envs\lmfit_cairo\lib\site-packages\matplotlib\pyplot.py", line 277, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "C:\Users\samue\Anaconda3\envs\lmfit_cairo\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\samue\Anaconda3\envs\lmfit_cairo\lib\site-packages\matplotlib\backends\backend_gtk3agg.py", line 5, in <module>
    from . import backend_cairo
  File "C:\Users\samue\Anaconda3\envs\lmfit_cairo\lib\site-packages\matplotlib\backends\backend_cairo.py", line 21, in <module>
    import cairocffi as cairo
  File "C:\Users\samue\Anaconda3\envs\lmfit_cairo\lib\site-packages\cairocffi\__init__.py", line 48, in <module>
    cairo = dlopen(
  File "C:\Users\samue\Anaconda3\envs\lmfit_cairo\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
```

I will see if this has been reported at matplotlib.

There's quite a lot of logic in `lmfit` to prevent this from happening.
The behavior of  `_@ensurematplotlib` decorator is set after trying to import `matplotlib.pyplot`.
The failing test checks against `matplotlib` only (ie: `pytest.importorskip("matplotlib"`). Consistently using the same import would prevent such an error from slipping through.

> My biggest regret with `lmfit` is agreeing to add `Model.plot`.

It is useful, but as I understand it's a maintenance nightmare ;).

**Comment by spalato** [comment]
Changing the importskip to: `pytest.importorskip("matplotlib.pyplot")` moves the issue there instead, probably since the import raises `OSError` instead of `ImportError`.

Marking the test with: `@pytest.mark.skipif(not lmfit.model._HAS_MATPLOTLIB, reason="requires matplotlib.pyplot")` successfully skips the test...

**Comment by spalato** [comment]
Somehow I cannot reproduce this in a clean environment with only matplotlib. Something confuses the configuration behind the scene.

**Comment by reneeotten** [comment]
> > I think it should be fine to install pure python modules like `lmfit` with `pip`.

True, but some packages are not pure Python and do require compilation; there the issue could come in.

> I think so too. (Can one manage the `python` version using `pip`?)
> To avoid problems, I ran:
> `conda create -n lmfit_dev python pip`, `pip install --no-cache -r ./requirements-dev.txt` and `pip install -e .`.
> 
> > * what version of `matplotlib` do you have installed? Do `import matplotlib` and `import matplotlib.pyplot as plt` work.
> 
> Surprisingly, the answers are: yes and no.
> 
> ```
> >>> import matplotlib
> >>> matplotlib.__version__
> '3.3.4'
> >>> import matplotlib.pyplot as plt
> Traceback (most recent call last):
>   File "C:\Users\samue\Anaconda3\envs\lmfit_cairo\lib\site-packages\matplotlib\backends\backend_cairo.py", line 15, in <module>
>     import cairo
> ModuleNotFoundError: No module named 'cairo'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\samue\Anaconda3\envs\lmfit_cairo\lib\site-packages\matplotlib\pyplot.py", line 2336, in <module>
>     switch_backend(rcParams["backend"])

You did make a new environment but the traceback shows that you were not using that one (instead it uses `lmfit_cairo`). Again, make a new environment, install everything with conda and see if the problem persists.

**Comment by spalato** [comment]
> You did make a new environment but the traceback shows that you were not using that one (instead it uses lmfit_cairo). Again, make a new environment, install everything with conda and see if the problem persists.

Sorry for that slight inconsistency. I installed `pycairo` in `lmfit_dev` in order to move on. I reproduced everything using the `lmfit_cairo` environment, which is entirely dedicated to this issue. 

I cannot reproduce the issue when installing matplotlib only, using pip. (ie: `conda create -n lmfit_dev python pip`, then `pip install matplotlib`).

When using conda, installing `cairosvg` installs `cairo` and `cairocffi`. (Conda can't find all the recipe for `sphinxcontrib-svg2pdfconverter`) All test pass.

As mentioned by @newville , this is an obscure dependency issue we can hunt down for days. (So far, it seems that installing cairosvg through pip causes an issue in matplotlib imports, on windows...) It doesn't seem the root cause is in lmfit. I'll keep hunting down a bit...

I suggest the following changes: 
1. Add `pycairo` to `requirements-dev.txt` (which already contains `matplotlib` and `cairosvg`)
2. Add the following conditional skip to `test_composite_plotting`: `@pytest.mark.skipif(not lmfit.model._HAS_MATPLOTLIB, reason="requires matplotlib.pyplot")`

I'll make a PR.

**Comment by spalato** [comment]
As expected, the following sequence reproduces the issue:

`conda create -n cairosvg_matplotlib python pip`
`pip install cairosvg`
`pip install matplotlib`
`python -c "import matplotlib.pyplot"`

`lmfit` is not involved in this. I'm not even sure where to report this to...

**Comment by reneeotten** [comment]
> I suggest the following changes:
> 
>     1. Add `pycairo` to `requirements-dev.txt` (which already contains `matplotlib` and `cairosvg`)
> 
>     2. Add the following conditional skip to `test_composite_plotting`: `@pytest.mark.skipif(not lmfit.model._HAS_MATPLOTLIB, reason="requires matplotlib.pyplot")`
> 
> 
> I'll make a PR.

I am pretty sure we will not add `pycairo` as a dependency; it is only needed for certain backends in `matplotlib`. The issue you're having is related to not having a working `matplotlib` installation, that's what you should fix instead.

Again, I say this once more: make conda environment and install the packages with `conda install .....` and stop using `pip`; only if you do that and can still show that this is causing a problem I might be convinced to look into it more. If you do this install only the minimum requirements (i.e., in requirements.txt + matplotlib) so that we can isolate whether there is some unintended side effect in installing the development requirements.

**Comment by reneeotten** [comment]
@spalato as you showed here and the issue you opened in `matplotlib` it has to do with installing `cairosvg`. That package installs `cairocffi` as a dependency and is -supposedly- a drop-in replacement for `pycairo`. That seems to work all fine on Linux/macOS but not on Windows for reasons that I do not nor will try to understand (but I can reproduce this on Azure pipelines when running under Windows).

@newville so even though it hasn't anything to do directly with `lmfit` we could conditionally, and only when using Windows, add `pycairo` as a dependency. In that case one should have a functional `matplotlib` package and changing the tests would be no longer necesarry - correct?

**Comment by newville** [comment]
@reneeotten @spalato I kind of think the right thing for lmfit to do is to allow 

```
 fig, ax = result.plot(show_init=True)
```

in `test_composite_plotting` to fail 

I recognize that this would sort of break the testing of the lmfit code that does plotting, but I'm not sure that we should be taking responsibility for failures that are basically from (the otherwise very well-tested) matplotlib.    Perhaps we could just put that `result.plot` in a try/except, expecting it to work but raising an error if it does not. 
Other opinions or ideas would be most welcome.
