### ISSUE TITLE
Voigt-Function throws error - with suggestion of solution

### ISSUE THREAD

**Issue by burstwacke** [lmfit/lmfit-py#727]
#### First Time Issue Code
Yes, I read the instructions and I am sure this is a GitHub Issue.

#### Description
When I try to use the VoigtModel it throws an AttributeError: 'Series' object has no attribute 'real'`
This applies for the functions "Model.fit()" and "Model.eval()". Maybe more, but I did not try them.

###### A Minimal, Complete, and Verifiable example
```import pandas as pd
from lmfit.models import VoigtModel

data = pd.read_table('someData.txt', header=4, names=["x","y"])
V = VoigtModel()
parmV = V.make_params(amplitude=4, center=10, sigma=0.5, gamma=0.5)
parmV['gamma'].set(vary=True, min=0) #Why not default???

fit = V.fit(data['y'],parmV,x=data['x'])
```

###### Error message:

```
Traceback (most recent call last):

  File "...\Anaconda3\lib\site-packages\lmfit\lineshapes.py", line 118, in voigt
    return amplitude*wofz(z).real / max(tiny, (sigma*s2pi))

  File "...\Anaconda3\lib\site-packages\pandas\core\generic.py", line 5465, in __getattr__
    return object.__getattribute__(self, name)

AttributeError: 'Series' object has no attribute 'real'
```

###### Version information
Python: 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]

lmfit: 1.0.2, scipy: 1.6.2, numpy: 1.20.2, asteval: 0.9.23, uncertainties: 3.1.5

###### Working solution

The issue seems to be related to the calculation of the real part of the wofz function within the "lineshapes.py" file line 118:

Current version: 
`return amplitude*wofz(z).real / max(tiny, (sigma*s2pi))`

Working solution:
`return amplitude*np.real(wofz(z)) / max(tiny, (sigma*s2pi))`

However, this requires to include numpy package.

**Comment by reneeotten** [comment]
@burstwacke thanks for the report. The problem isn't specific to the `Voigt` function; `pandas` has removed the `Series.real()` method. That happened already back in version 1.0.0 as I just read in their release notes. 

I guess nobody has tried to use a `pandas.Series` with `lmfit` since then and we don't have a great test coverage for the use with `pandas` so nobody noticed. I think this should likely be fixed somewhere somewhere "higher up" than in the lineshape functions; we just need to look where.

**Comment by newville** [comment]
@burstwacke @reneeotten  I agree with Renee's assessment. 

It seems like using pandas Series works right up until the point when it doesn't.... 
But we've seen other issues with shape and datatypes with these functions too.   
Perhaps we a decorator on all (most?) of the lineshape functions to ensure that the `x` value is  `x = np.asarray(x, dtype='float64') `.

**Comment by burstwacke** [comment]
Ahh, thanks for the explanation.
That would explain, why some scripts stopped working. (I feard that the failure was sitting in front of the PC...)

I'll test various models within the next days. As soon as I see anything else, I'll include it here.

**Comment by burstwacke** [comment]
I'd like to suggest to replace line 117 in lineshapes.py in the following way:

old:
    `return amplitude*wofz(z).real / max(tiny, (sigma*s2pi))`
new:
    `return amplitude*real(wofz(z)) / max(tiny, (sigma*s2pi))`

This will solve the issue above.
(And I don't have to change my lmfit files manually.) :)

**Comment by newville** [comment]
@burstwacke  This is sort of a complicated topic.  I should say that I don't have a strong affinity for supporting pandas Series.   While `scipy.special.wofz` of a pandas Series will return a complex pandas Series, it turns out that complex pandas Series are broken by not having a `real` attribute.    The brokenness of pandas Series is sort of the real problem here.  Anything we do here is a workaround: we cannot actually "support" pandas or other nd-array-like derivatives.  We can *hope* they work, but we probably shouldn't.

```
wofz(z).real                # 1: expects input to just work. "Hope".
np.real(wofz(z))            # 2: coerces the output of a scipy function ... why do we need to do that?
wofz(np.asfarray(z)).real   # 3: coerces the *input* so that the scipy/numpy results work "corrrectly.
 ```

I would think that option "# 3" is the most sustainable and resiliant.  This sort of seems like it should happen even for "np.sin()" and happen "late in the process", so `np.sin(np.asfarray(x))`, etc.   

Based on recent conversations such as https://groups.google.com/g/lmfit-py/c/nrecDPD8VT0, I'm more of the opinion that we should not be coercing all input data by default before fitting starts.  

I think a better approach would be that the built-in model functions should probably do the `np.asfarray()` coercion inside the function and that we should coerce the array output from the objective/model before sending it to the underlying solver.
