### ISSUE TITLE
remove codecov from CI

### ISSUE THREAD

**Issue by newville** [lmfit/lmfit-py#733]
The automated reports from codecov are not a reliable measure of code quality.  

The code I added for #732 is ALL covered in the tests, and codecov reported Failure. 

Coverage is a useful but not reliable, sufficient, or definitive measure of code quality.  Using it in a game-like manner is as an approach to improving coverage is a bad idea.

Worse, codecov is just wrong in its reporting.

**Comment by reneeotten** [comment]
I don't think there is anything wrong with the `codecov`, in fact to me it seems to work perfectly fine. Its *initial* report is often not correct as in that case only the tests for one Python version (e.g., with minimal or all dependencies) has finished. It will update once the other coverage becomes available and then it the report is fine.

**Comment by newville** [comment]
@reneeotten You mean it's OK that the initial report is wrong because then it gets fixed?   
So, is it fair to say that it is sometimes wrong and should not be read as a reliable report?

**Comment by reneeotten** [comment]
@newville I am not saying this behavior is right or wrong - just trying to explain what is happening and why... 

As soon as one of the tests (with one of the Python versions and minimal/current dependencies) is finished the coverage result is uploaded and the `codecov` bot comments on the PR. Since that one specific result will be always covering less than once the full test-suite is completed, the immediate result from the `codecov` bot will report a failure. Once the tests with combinations of other Python versions and dependencies finish and upload their coverage result, the `codecov` bot will update its report in the PR. Once the full test-suite has finished and uploaded its coverage results the report from `codecov` *is* reliable and can be trusted. 

So I guess your point is that the `codecov` bot should only comment in the PR once it has received *all* the results and combined them into a final report, correct? I agree that this would be ideal - I tried to do that when we changed to Azure pipelines, but couldn't figure out how. I am happy to look into this again and see if that can be accomplished; otherwise just waiting until the complete test-suite has finished (as we would anyway do to make sure that everything works as intended for different combinations of Python versions and dependencies) is the alternative "solution".

**Comment by newville** [comment]
@reneeotten   The coverage report depend on Python version because some library is not available with some testing environments?   That seems like a problem with codecov comparing apples to oranges.   The problem is not in our code, or in the amount of coverage to tests provide, but with the concept of measuring coverage.

I think my bigger complaint is that codecov reports "success" or "failure" at all and that Github reports "success" only if all CI tools report "success".   Codecov interprets any increase in coverage as success and any decrease in coverage as a failure.  That means that one can demonstrably improve the code, say by adding a line break and have that be reported as a coverage failure.  Or, one can remove an error message in an unusual but possible except block that we don't have a test for (what if a file on a network share goes away?) which makes the code worse and is a "success". 

It would be great to see the coverage report: "coverage is currently at 93.512%, see here for details", but "failure" (and "success") are misguided.

**Comment by reneeotten** [comment]
> @reneeotten The coverage report depend on Python version because some library is not available with some testing environments? That seems like a problem with codecov comparing apples to oranges. The problem is not in our code, or in the amount of coverage to tests provide, but with the concept of measuring coverage.

No, it does depend on our code and how we do the tests. In case we use "minimal" dependencies, we only install the absolute requirements and not things like `dill`, `pandas`, etcetera. So yes, the test coverage of *our* code depends on that fact, since tests are skipped depending on whether packages are available or not. Additionally we have stuff in the codebase that will do something different if `dill` is installed or not, so how much of that code is accessed depends on whether we use the "minimal" or "current" (i.e., all optional dependencies). There is no way around that.

> I think my bigger complaint is that codecov reports "success" or "failure" at all and that Github reports "success" only if all CI tools report "success". Codecov interprets any increase in coverage as success and any decrease in coverage as a failure. That means that one can demonstrably improve the code, say by adding a line break and have that be reported as a coverage failure. Or, one can remove an error message in an unusual but possible except block that we don't have a test for (what if a file on a network share goes away?) which makes the code worse and is a "success".

Adding a line break will (or at least should) not cause any failure. I agree that adding removing some error message in a block for which we don't have tests can fail the "diff coverage" (as happened for example in the `f-string` PR). Even though that could improve the "overall" test coverage since you removed lines, that will not be reported as an success since the "diff" coverage is not complete.

> It would be great to see the coverage report: "coverage is currently at 93.512%, see here for details", but "failure" (and "success") are misguided.

All these options can likely be configured with `codecov` and I am happy to look into that.

**Comment by newville** [comment]
> No, it does depend on our code and how we do the tests. In case we use "minimal" dependencies, we only install the absolute requirements and not things like dill, pandas, etcetera. So yes, the test coverage of our code depends on that fact, since tests are skipped depending on whether packages are available or not. Additionally we have stuff in the codebase that will do something different if dill is installed or not, so how much of that code is accessed depends on whether we use the "minimal" or "current" (i.e., all optional dependencies). There is no way around that.

Well, if codecov could be told to compare results from other specific tests, say the last time it ran the tests without `pandas` available, maybe that would be better.  But I don't think it actually matters.   

The problem is not in our code or our tests.  Rather it is that `codecov` makes a questionable measurement and then presents the results as "pass/fail". 

I cannot think of a situation where a "failure" from `codecov` is ever useful or should be a reason not to merge code.   A lack of tests for new code, yes, a `codecov` failure based on the change in coverage fraction, no.     
I like the report that shows what code is not covered at all, but since that binary, it's not really that informative -- Yes means "at least 1 test ran through that line of code without failing".    That metric is not something that "fails" or "passes".

**Comment by newville** [comment]
@reneeotten OK, Thanks for all of this!
