### ISSUE TITLE
`ConstantModel` returns wrong shape

### ISSUE THREAD

**Issue by JeppeKlitgaard** [lmfit/lmfit-py#840]
I am guessing people very rarely use the built-in `ConstantModel` without combining it with another model, which is probably why this hasn't cropped up before (when combined broadcasting rules would sort this out, I suspect), but `ConstantModel` returns only a single element rather than matching the shape of the input data. This causes the following to fail:

```python
import numpy as np
import matplotlib.pyplot as plt
from lmfit.models import ConstantModel

x = np.array([1.0, 2.0, 3.0])
y = np.array([1.0, 1.5, 0.5])
model = ConstantModel()
params = model.guess(y, x=x)
fit = model.fit(y, params, x=x)

plt.plot(x, y, "o")
plt.plot(x, fit.best_fit, "--")
```

This raises: `ValueError: x and y must have same first dimension, but have shapes (3,) and (1,)` since `fit.best_fit` has shape `(1,)`.

**Comment by newville** [comment]
@JeppeKlitgaard This has come up before, see #684.

I think the misunderstanding is that lmfit does not require (and tries very hard to not expect) independent variables to be of any particular shape or even data type.  `ConstantModel` does take an independent variables `x` as a first argument, but it completely ignores it.   That is, it returns the value of `c` (a scalar). 

It does not return `c*np.ones(x.shape)`, basically because it does not demand that `x` have a shape.
