### ISSUE TITLE
New version of lmfit does't work,  version 1.0.3 does. Something has changed

### ISSUE THREAD

**Issue by pnachtwey** [lmfit/lmfit-py#877]
Yes, I read the instructions and I am sure this is a GitHub Issue.

I just realized that code that I haven't changed since Nov 2022 does work with the new lmfit
I pulled my hair out trying to find a bug.  I am fitting a 15 parameter function to 3040 data points.
The old 1.03 works perfectly.  The new 1.21 seems to have a problem with the line search.  After taking a step in each of the 15 dimensions the next point returns some very high sum of squared errors.  The old 1.03 doesn't do this.
I get an error with the new code saying
##  Warning: uncertainties could not be estimated:

When I run some older version of my code that I restored from file history I get this error

Warning (from warnings module):
  File "C:\Users\pnach\AppData\Roaming\Python\Python311\site-packages\lmfit\printfuncs.py", line 187
    spercent = f'({abs(par.stderr/par.value):.2%})'
RuntimeWarning: divide by zero encountered in scalar divide

There is no error message about where  the problem is in my code.  if there was I could trace it down but I don't know the calling sequence to get to the warning above.

I am familiar with how the Levenberg-Marquardt function works as we have it implemented in some of our products.

**Comment by pnachtwey** [comment]
I tried version 1.1.0.   It works,
Version 1.20 does not
I zipped the code and the data file.  It is 115K   The website wouldn't accept the file.

**Comment by newville** [comment]
@pnachtwey 
> Yes, I read the instructions and I am sure this is a GitHub Issue.

I am not so sure.   As we say in the guidelines for submitting an issue, getting a "bad fit" is not an issue. We recommend for new users start a conversation on the mailing list or Github discussions.  The instructions for submitting an issue clearly say to include a minimal example that shows the problem.  

It is not clear what behavior you are describing.  Is it "Warning: uncertainties could not be estimated:".  If so, that is a warning, not really an error.  

But you also mention an error of 
```
Warning (from warnings module):
File "C:\Users\pnach\AppData\Roaming\Python\Python311\site-packages\lmfit\printfuncs.py", line 187
spercent = f'({abs(par.stderr/par.value):.2%})'
RuntimeWarning: divide by zero encountered in scalar divide
```

which is sort of weird.   The code there is 
```
        if par.stderr is not None:
            serr = gformat(par.stderr)
            try:
                spercent = f'({abs(par.stderr/par.value):.2%})'
            except ZeroDivisionError:
                spercent = ''
```

That is, we are clearly looking for divide-by-zero.  I suppose one could get a TypeError, though that seems hard to understand.  I see how one gets a RuntimeWarning.  Is that from a numpy divide-by-zero??  That would imply that `par.value` or `par.stderr` was a numpy value.

You will have to provide a minimal working example for us to understand what is happening.

**Comment by pnachtwey** [comment]
This isn't a bad fit problem.   There is a significant difference between 1.1.0 and the next versions.
I tried different versions.   I finally was able to submit the whole file which isn't that big and the data which is big.
I am trying to fit a function that will simulate a non-linear valve.   If the program works it will take several minutes and draw 3 plots.  You many need to change where the file valve3.txt is located or the path to valve3.txt
[ValveID-10seg.zip](https://github.com/lmfit/lmfit-py/files/11413996/ValveID-10seg.zip)

**Comment by reneeotten** [comment]
did you go through the release notes to check what might have been changes between versions that work and don't? For example, you might want to look into "epsfun" or check whether the change in core ion of input data might have any effect on your specific case (it shouldn't).

I haven't looked at what you send here - downloading a random zip files is not a MWE.

**Comment by newville** [comment]
@pnachtwey Yeah, if we "may need to change" something, that is not a minimal example.   I tried running your example and got
```
File "/Users/Newville/Downloads/Valv/ValveID-10seg.py", line 14, in <module>
    from readRMCPlotsCSV import readRMCPlot
ModuleNotFoundError: No module named 'readRMCPlotsCSV'
```

It looks like your data file would probably be readable as plain tab-separated text file, but we do not know what your reader does.   You could just remove all of the plotting code and hardwire the data into your script.

You say there is a significant difference, but you have not shown that.  There are no reports of results.  The only traceback you posted seems very strange, as if the data types of the Parameters are messed up.  It is hard for me to guess how that could happen.   

Look, we are willing to help you track this problem down, but if you want assistance you will have to provide more and complete information that actually shows the actual problem.

**Comment by pnachtwey** [comment]
[ValveID.zip](https://github.com/lmfit/lmfit-py/files/11421684/ValveID.zip)
This zip file includes all that is needed.   I tried it out in a separate directory.   It should display the sum of errors squared for about 10 minutes then show 3 graphs if you use 1.1.0.  The later versions will do one iteration of 15 steps OK then then next iteration the numbers go wild and the minimization quits.

**Comment by pnachtwey** [comment]
But what is the difference between 1.1.0 where my code works and 1.2.0 where it doesn't?
My starting positions are typical for a valve.
The reason there is a low limit for g1,g2,g3 is that a negative value would mean the flow of oil would go the wrong way when it doesn't/can't.   The valve has a dead band where the output up to about 20% should yield no flow.  Notice that each gain segment adds to the others before it.  This way I can assume the flow for 80% is the same as 60% even if I don't have a control signal that goes above 80%.  The value a1 is the natural frequency of the valve in radians per second squared.   100 rad/sec is not fast.  The a2 is 2 times the damping factor time the natural frequency.   The damping factor is typically around 0.3 to 0.4.   My initial guesses are typical.

I don't understand what makes 1.1.0 work and 1.2.0 fail using EXACTLY the same code, initial conditions and data.
BTW,  I did look for epsfun and didn't find anything about it.
I have reverted my lmfit to 1.1.0 for now.

**Comment by newville** [comment]
@pnachtwey 

> But what is the difference between 1.1.0 where my code works and 1.2.0 where it doesn't?

As I have tried to explain above, "Code working" and "Getting a good fit" are different things.  Your code does work with both versions (and in that sense,  I again suggest that this is not really an issue with the lmfit library) -- no error messages are produced.  Neither lmfit 1.1.0 nor 1.2 give very good results with your code.

With lmfit 1.1.0, your code leaves at least 3 of the parameters at the initial values.  That indicates that the fit did not work well.  

>The reason there is a low limit for g1,g2,g3 is that a negative value would mean the flow of oil would go the wrong way when it doesn't/can't. ...  

That is all fine. Having a boundary is fine.  As you will have read in my earlier suggestion, I did not suggest removing these limits.  I did not remove these limits. I did not change the initial values for `ratio`, `a1`, or `a2`.  

What I suggested and demonstrated with changes to your code, was to change the starting values to be both a) away from any boundary value, and b) to not be exactly "0", but to be a small value of about the expected magnitude.   

Really, 0.001 is infinitely larger than 0.   When you guess "0" the method has no way of knowing what sort of magnitude to expect.  In fact, it assumes you meant around 1.e-8.  If you really mean "around 0.001", that guess is off by 5 orders of magnitude.  Yes, no kidding. 

> I don't understand what makes 1.1.0 work and 1.2.0 fail using EXACTLY the same code, initial conditions and data.

I think we have different definitions of "work" and "fail".   Your fit with 1.1.0 is not good.  The fit I showed with non-zero initial values appears to be better with 1.2.0 than with 1.1.0, though I hesitate to assert that it is significantly better.

As I said earlier (and, really, I have spent a lot of time trying to help you with this non-Issue and my patience, willingness, and ability to help people is not infinite), the only thing I can think of that changed that might be relevant is the default value of `epsfcn`.  You said in your original post that you were familiar with L-M method, so I optimistically assumed you knew that this value sets the step size for calculating the finite-difference Jacobian.  You could try altering this value, but I suspect it won't help that much unless you also change the actual problem that the initial values should be both away from the boundaries and away from 0 to be approximately the right order of magnitude.

Again, and in conclusion:  

1. initial values **ALWAYS** matter.
2. do **NOT** have initial values at boundary values.
3. initial values of "0" often make fits much harder (ie, more function evaluations) and prone to poor results. 
4. always read the fit report.  The next time you submit an Issue or a question, you will include the output text of the fit report and complete error messages.  Your original post had a snippet of a message that could not be reproduced. 

I think this does not show any real issue with the lmfit code.  I do think it is worth keeping open the possibility that the change of the default value for `epsfcn` from 1.e-15 to 1.e-10 needs re-examination.  I have not seen a clear case where this makes things worse (the results I showed above might even suggest it improves things!), but that was partially reported (no example provided) and I could be persuaded otherwise, perhaps to dial that back to 1.e-12 or so.
