### ISSUE TITLE
The `prefix` string is not added to parameter names for `CompositeModel`s

### ISSUE THREAD

**Issue by jcjaskula-aws** [lmfit/lmfit-py#954]
#### Description
Strings passed via `prefix` when constructing a `CompositeModel` should be propagated to each parameter. Currently, it is missing for direct parameters (e.g. `amplitude` below) but properly used with derived parameters (like `sigma`).

###### A Minimal, Complete, and Verifiable example
```
from lmfit.models import GaussianModel, ConstantModel
from lmfit.model import CompositeModel
import operator
mm=CompositeModel(GaussianModel(prefix="G_"), ConstantModel(prefix="C_"), operator.add, prefix="prefix_")
mm.make_params()
```
returns
<img width="767" alt="image" src="https://github.com/lmfit/lmfit-py/assets/99367153/03ab8af6-ab1a-4352-9aa6-befadc7ffcaa">

`mm.prefix` returns the string `prefix_`. 

I would expect `prefix_G_amplitude`, `prefix_G_center`, `prefix_G_sigma`, `prefix_C_c` and the derived parameters to have expressions using the just-mentioned parameters. 

###### Version information
Python: 3.10.14 (main, Mar 19 2024, 21:46:16) [Clang 15.0.0 (clang-1500.3.9.4)]

lmfit: 1.3.1.post0+g3cfd09a1.d20240424, scipy: 1.11.4, numpy: 1.26.3,asteval: 0.9.32, uncertainties: 3.1.6

**Comment by newville** [comment]
@jcjaskula-aws I'm not sure I agree with your "should" here.   I am not even certain that "prefix" makes sense with a Composite Model.   You clearly said that the Gaussian Model should have a prefix of 'G_'.

The things that look to me like they need fixing are: a) that 'prefix_' got used as a prefix for the derived parameters, and b) how did 'prefix_G_sigma' get defined.  

Disallowing 'prefix' with `CompositeModel` might be the most sensible fix.

(And, yes, no apologies for the delay in responding to this, since you chose to call it an Issue instead of a Discussion).
